import { CareerRoadmap } from "../types/knowNext.types";

export const ROADMAPS: CareerRoadmap[] = [
  {
    id: "rm-data-scientist",
    careerId: "c-data-scientist",
    careerTitle: "Data Scientist",
    icon: "🧬",
    applicableStages: ["afterGraduation", "workingProfessional"],
    totalSteps: 7,
    estimatedDuration: "3-4 years",
    steps: [
      { id: "s1", order: 1, title: "Master Mathematics & Statistics", description: "Build the quantitative foundation: linear algebra, probability, statistics, and calculus.", type: "skill", duration: "3 months", certifications: [], skillsRequired: ["Linear Algebra", "Probability", "Statistics"], resources: ["Khan Academy", "MIT OCW 18.06", "Statistics with Python (Coursera)"], status: "completed" },
      { id: "s2", order: 2, title: "Learn Python Programming", description: "Become proficient in Python — the primary language of data science.", type: "skill", duration: "2 months", certifications: [], skillsRequired: ["Python", "NumPy", "Pandas", "Matplotlib"], resources: ["Python.org", "Automate the Boring Stuff", "Kaggle Python Course"], status: "completed" },
      { id: "s3", order: 3, title: "Learn SQL & Databases", description: "Query and manage relational databases for real-world data extraction.", type: "skill", duration: "1 month", certifications: [], skillsRequired: ["SQL", "PostgreSQL", "Data Modeling"], resources: ["SQLBolt", "Mode Analytics SQL", "PostgreSQL docs"], status: "current" },
      { id: "s4", order: 4, title: "Machine Learning Fundamentals", description: "Study supervised/unsupervised learning, model evaluation, and feature engineering.", type: "certification", duration: "3 months", certifications: ["Coursera ML Specialization (Andrew Ng)"], skillsRequired: ["Scikit-learn", "Regression", "Classification", "Clustering"], resources: ["Andrew Ng ML Course", "Hands-On ML (Book)", "fast.ai"], status: "locked" },
      { id: "s5", order: 5, title: "Build Real-World Projects", description: "Work on 3-5 data science projects — Kaggle competitions, personal datasets, or internships.", type: "project", duration: "3 months", certifications: [], skillsRequired: ["End-to-end ML", "EDA", "Model Deployment"], resources: ["Kaggle", "GitHub", "DrivenData"], status: "locked" },
      { id: "s6", order: 6, title: "Deep Learning & Advanced AI", description: "Master neural networks, CNNs, RNNs, transformers, and production ML.", type: "certification", duration: "4 months", certifications: ["Deep Learning Specialization", "TensorFlow Developer"], skillsRequired: ["TensorFlow", "PyTorch", "NLP", "Computer Vision"], resources: ["DeepLearning.AI", "fast.ai", "Hugging Face"], status: "locked" },
      { id: "s7", order: 7, title: "Data Science Interview Prep & Job Hunt", description: "Practice LeetCode, statistics interviews, ML system design, and build a strong portfolio.", type: "experience", duration: "2 months", certifications: [], skillsRequired: ["System Design", "ML Interviews", "Portfolio Building"], resources: ["Leetcode", "StrataScratch", "ML Design interview resources"], status: "locked" },
    ],
  },
  {
    id: "rm-software-engineer",
    careerId: "c-software-engineer",
    careerTitle: "Software Engineer",
    icon: "💻",
    applicableStages: ["after12th", "afterGraduation", "workingProfessional"],
    totalSteps: 6,
    estimatedDuration: "1-2 years",
    steps: [
      { id: "s1", order: 1, title: "Learn Programming Fundamentals", description: "Master one programming language (Python or Java) and understand core CS concepts.", type: "skill", duration: "2 months", certifications: [], skillsRequired: ["Python/Java", "OOP", "Logic Building"], resources: ["CS50 (Harvard)", "Python for Everybody (Coursera)", "Java Brains"], status: "completed" },
      { id: "s2", order: 2, title: "Data Structures & Algorithms", description: "The foundation of technical interviews — arrays, trees, graphs, DP.", type: "skill", duration: "3 months", certifications: [], skillsRequired: ["DSA", "Problem Solving", "Big-O"], resources: ["LeetCode", "GFG DSA Sheet", "Striver's A2Z DSA Course"], status: "current" },
      { id: "s3", order: 3, title: "Web / Mobile Development", description: "Choose a specialization — frontend (React), backend (Node/Django), or mobile (Flutter).", type: "skill", duration: "3 months", certifications: [], skillsRequired: ["React/Flutter", "REST APIs", "Git", "Databases"], resources: ["React docs", "The Odin Project", "Flutter.dev"], status: "locked" },
      { id: "s4", order: 4, title: "Build Portfolio Projects", description: "Create 2-3 full-stack projects with GitHub repos, live demos, and documentation.", type: "project", duration: "2 months", certifications: [], skillsRequired: ["Full-Stack Dev", "Deployment", "Version Control"], resources: ["GitHub", "Vercel", "Render"], status: "locked" },
      { id: "s5", order: 5, title: "Get Internship / Entry-Level Job", description: "Apply to startups, product companies, or service companies. Build real-world experience.", type: "experience", duration: "6 months", certifications: [], skillsRequired: ["Communication", "Team Collaboration", "Agile"], resources: ["LinkedIn", "Internshala", "AngelList"], status: "locked" },
      { id: "s6", order: 6, title: "Advanced: System Design & Architecture", description: "For senior roles — learn to design scalable systems, microservices, and cloud infrastructure.", type: "skill", duration: "3 months", certifications: ["AWS Developer Associate"], skillsRequired: ["System Design", "Cloud", "CI/CD", "Microservices"], resources: ["Grokking System Design", "ByteByteGo", "AWS Training"], status: "locked" },
    ],
  },
  {
    id: "rm-doctor",
    careerId: "c-doctor",
    careerTitle: "Medical Doctor (MBBS)",
    icon: "🩺",
    applicableStages: ["after12th"],
    totalSteps: 6,
    estimatedDuration: "8-11 years",
    steps: [
      { id: "s1", order: 1, title: "10+2 with PCB & NEET Preparation", description: "Study Physics, Chemistry, Biology at the 12th level and prepare intensively for NEET.", type: "education", duration: "2 years", certifications: [], skillsRequired: ["PCB", "NEET Preparation"], resources: ["Relicus Entrance Coaching (NEET)", "Allen", "Aakash"], status: "completed" },
      { id: "s2", order: 2, title: "Crack NEET & Secure MBBS Admission", description: "Appear in NEET, get merit-based admission to government or private medical college.", type: "certification", duration: "1 attempt", certifications: ["NEET Scorecard"], skillsRequired: ["NEET Preparation", "Exam Strategy"], resources: ["NEET Previous Papers", "NMC guidelines"], status: "completed" },
      { id: "s3", order: 3, title: "MBBS (Years 1-2): Pre-Clinical", description: "Study Anatomy, Physiology, Biochemistry — the foundations of medicine.", type: "education", duration: "2 years", certifications: [], skillsRequired: ["Anatomy", "Physiology", "Biochemistry"], resources: ["Gray's Anatomy", "Ganong's Physiology", "Lehninger Biochemistry"], status: "current" },
      { id: "s4", order: 4, title: "MBBS (Years 3-4): Para-Clinical & Clinical", description: "Study Pathology, Pharmacology, Medicine, Surgery, and OBG with hospital rotations.", type: "education", duration: "2.5 years", certifications: [], skillsRequired: ["Clinical Diagnosis", "Pharmacology", "Pathology"], resources: ["Davidson's Medicine", "Bailey & Love Surgery", "Park's PSM"], status: "locked" },
      { id: "s5", order: 5, title: "Internship (Compulsory Rotating)", description: "12-month rotating internship across all departments in a teaching hospital.", type: "experience", duration: "1 year", certifications: ["MBBS Degree"], skillsRequired: ["Clinical Skills", "Patient Management"], resources: ["Hospital training"], status: "locked" },
      { id: "s6", order: 6, title: "PG (MD/MS) Specialization", description: "Appear in NEET-PG to specialize in a field of medicine.", type: "certification", duration: "3 years", certifications: ["MD/MS Degree"], skillsRequired: ["Specialization expertise", "Research"], resources: ["NEET-PG prep", "UpToDate", "BMJ"], status: "locked" },
    ],
  },
  {
    id: "rm-ux-designer",
    careerId: "c-ux-designer",
    careerTitle: "UX/UI Designer",
    icon: "🎨",
    applicableStages: ["after12th", "afterGraduation", "workingProfessional"],
    totalSteps: 6,
    estimatedDuration: "1-2 years",
    steps: [
      { id: "s1", order: 1, title: "Learn Design Foundations", description: "Study typography, colour theory, layout principles, and visual hierarchy.", type: "skill", duration: "1 month", certifications: [], skillsRequired: ["Typography", "Colour Theory", "Grid System"], resources: ["Canva Design School", "Coursera Graphic Design", "YouTube: Flux Academy"], status: "completed" },
      { id: "s2", order: 2, title: "Master Figma", description: "Become proficient in Figma — the industry-standard design tool.", type: "skill", duration: "2 months", certifications: ["Figma Certification (unofficial)"], skillsRequired: ["Figma", "Prototyping", "Components", "Auto Layout"], resources: ["Figma.com/learn", "Design with Figma (Coursera)", "DesignCode"], status: "completed" },
      { id: "s3", order: 3, title: "Learn UX Research & User Psychology", description: "Understand user research methods, usability testing, personas, and journey mapping.", type: "certification", duration: "2 months", certifications: ["Google UX Design Certificate"], skillsRequired: ["User Research", "Personas", "Usability Testing", "A/B Testing"], resources: ["Google UX Design Certificate (Coursera)", "Nielsen Norman Group articles"], status: "current" },
      { id: "s4", order: 4, title: "Build a Portfolio (3-5 Case Studies)", description: "Design real or concept projects with full case studies — problem, research, solution, outcome.", type: "project", duration: "3 months", certifications: [], skillsRequired: ["End-to-end Design", "Presentation", "Storytelling"], resources: ["Dribbble", "Behance", "Portfolio.adobe.com"], status: "locked" },
      { id: "s5", order: 5, title: "Internship & Real-World Practice", description: "Get internship at a product company, design agency, or startup.", type: "experience", duration: "3-6 months", certifications: [], skillsRequired: ["Collaboration", "Design Sprints", "Feedback Handling"], resources: ["LinkedIn", "Internshala", "AngelList Talent"], status: "locked" },
      { id: "s6", order: 6, title: "Specialise: Motion, Design Systems, or Product", description: "Choose a path — Motion Design (After Effects), Design Systems (Tokens), or Product (PM+Design).", type: "skill", duration: "2 months", certifications: [], skillsRequired: ["Motion Design / Design Systems / Product Thinking"], resources: ["Motion Design School", "Specify", "Tokens Studio"], status: "locked" },
    ],
  },
  {
    id: "rm-ca",
    careerId: "c-chartered-accountant",
    careerTitle: "Chartered Accountant (CA)",
    icon: "📊",
    applicableStages: ["after12th", "afterGraduation"],
    totalSteps: 5,
    estimatedDuration: "4-5 years",
    steps: [
      { id: "s1", order: 1, title: "CA Foundation", description: "Clear the CA Foundation exam (4 papers): Accounts, Maths, Business Laws, Economics.", type: "certification", duration: "4 months", certifications: ["CA Foundation"], skillsRequired: ["Accounting", "Mathematics", "Business Laws"], resources: ["ICAI Study Material", "ICAI Mock Tests"], status: "completed" },
      { id: "s2", order: 2, title: "CA Intermediate (Group 1 & 2)", description: "Clear 8 papers in two groups covering taxation, cost accounting, auditing, financial management.", type: "certification", duration: "12-18 months", certifications: ["CA Intermediate"], skillsRequired: ["Taxation", "Cost Accounting", "Auditing", "Financial Management"], resources: ["ICAI Study Material", "ICAI RTP", "Coaching institutes"], status: "current" },
      { id: "s3", order: 3, title: "Articleship (Mandatory Training)", description: "3-year mandatory articleship under a practicing CA — real-world exposure.", type: "experience", duration: "3 years", certifications: [], skillsRequired: ["GST Filing", "Income Tax", "Audit", "Company Law"], resources: ["ICAI Articleship Portal", "Working at a CA firm"], status: "locked" },
      { id: "s4", order: 4, title: "CA Final (Group 1 & 2)", description: "The ultimate exam — Financial Reporting, Strategic FM, Direct & Indirect Tax, Advanced Auditing.", type: "certification", duration: "12-18 months", certifications: ["CA Final"], skillsRequired: ["Advanced Accounting", "Strategic Financial Management", "Advanced Tax"], resources: ["ICAI Study Material", "Coaching: IPCC, RTP, MTP"], status: "locked" },
      { id: "s5", order: 5, title: "ICAI Membership & Career Launch", description: "Become a Fellow Member of ICAI and choose your career — practice, industry, or Big 4.", type: "experience", duration: "Ongoing", certifications: ["ACA / FCA Membership"], skillsRequired: ["CA Practice", "Client Management"], resources: ["ICAI Membership Portal", "LinkedIn", "Big 4 career portals"], status: "locked" },
    ],
  },
  {
    id: "rm-ai-engineer",
    careerId: "c-ai-engineer",
    careerTitle: "AI Engineer",
    icon: "🤖",
    applicableStages: ["afterGraduation", "workingProfessional"],
    totalSteps: 6,
    estimatedDuration: "2-3 years",
    steps: [
      { id: "s1", order: 1, title: "Python + ML Foundations", description: "Strong Python skills, NumPy, Pandas, Scikit-learn, and core ML concepts.", type: "skill", duration: "3 months", certifications: [], skillsRequired: ["Python", "NumPy", "Pandas", "Scikit-learn", "ML Basics"], resources: ["Kaggle Learn", "fast.ai Part 1", "Andrew Ng ML Specialization"], status: "completed" },
      { id: "s2", order: 2, title: "Deep Learning (PyTorch/TensorFlow)", description: "Master neural networks, CNNs, RNNs, attention mechanisms, and transformers.", type: "certification", duration: "4 months", certifications: ["Deep Learning Specialization (DeepLearning.AI)"], skillsRequired: ["PyTorch", "Neural Networks", "CNNs", "Transformers"], resources: ["DeepLearning.AI Specialization", "fast.ai", "Andrej Karpathy lectures"], status: "completed" },
      { id: "s3", order: 3, title: "LLMs & Generative AI", description: "Work with large language models, fine-tuning, RAG architectures, and AI agents.", type: "certification", duration: "3 months", certifications: ["LangChain Certification"], skillsRequired: ["Hugging Face", "LangChain", "RAG", "Prompt Engineering", "RLHF"], resources: ["Hugging Face Course", "LangChain docs", "OpenAI Cookbook"], status: "current" },
      { id: "s4", order: 4, title: "MLOps & Production AI Systems", description: "Deploy, monitor, and scale ML models in production using cloud and DevOps practices.", type: "skill", duration: "2 months", certifications: ["AWS ML Specialty"], skillsRequired: ["Docker", "Kubernetes", "MLflow", "CI/CD for ML", "Data Pipelines"], resources: ["MLOps Specialization (Coursera)", "Made with ML", "AWS SageMaker"], status: "locked" },
      { id: "s5", order: 5, title: "AI Research Paper Reading & Replication", description: "Read top AI papers (ArXiv) and implement key architectures from scratch.", type: "project", duration: "Ongoing", certifications: [], skillsRequired: ["Research Skills", "Paper Implementation", "Experimentation"], resources: ["Papers with Code", "ArXiv", "Two Minute Papers"], status: "locked" },
      { id: "s6", order: 6, title: "Build AI Products & Get Hired", description: "Build end-to-end AI applications and apply to AI-first companies.", type: "experience", duration: "2 months", certifications: [], skillsRequired: ["AI Product Development", "API Integration", "System Design"], resources: ["Product Hunt", "LinkedIn", "AI job boards"], status: "locked" },
    ],
  },
  {
    id: "rm-lawyer",
    careerId: "c-lawyer",
    careerTitle: "Corporate Lawyer",
    icon: "⚖️",
    applicableStages: ["after12th", "afterGraduation"],
    totalSteps: 5,
    estimatedDuration: "5-6 years",
    steps: [
      { id: "s1", order: 1, title: "Crack CLAT / AILET", description: "Prepare and clear law entrance exams to secure admission to NLUs or top law schools.", type: "certification", duration: "1-2 years prep", certifications: ["CLAT Scorecard"], skillsRequired: ["Legal Aptitude", "English", "GK", "Logical Reasoning"], resources: ["CLAT Possible", "LegalEdge", "Previous year papers"], status: "completed" },
      { id: "s2", order: 2, title: "BA LLB (5 Years)", description: "Study constitutional law, corporate law, civil procedure, criminal law, and electives.", type: "education", duration: "5 years", certifications: [], skillsRequired: ["Legal Research", "Moot Courts", "Drafting", "Research Papers"], resources: ["SCC Online", "Manupatra", "Legal textbooks"], status: "current" },
      { id: "s3", order: 3, title: "Moot Courts & Internships", description: "Participate in moot courts, legal clinics, and intern at law firms and courts.", type: "experience", duration: "Throughout LLB", certifications: [], skillsRequired: ["Oral Advocacy", "Brief Writing", "Client Interaction"], resources: ["National Moot Court competitions", "Law firm internships"], status: "locked" },
      { id: "s4", order: 4, title: "Bar Council Enrollment & Junior Advocacy", description: "Enroll at Bar Council, choose district court or high court practice, and find a senior advocate to learn under.", type: "certification", duration: "2-3 years", certifications: ["Bar Council Enrollment"], skillsRequired: ["Court Practice", "Client Management", "Brief Drafting"], resources: ["Bar Council of India portal", "High Court websites"], status: "locked" },
      { id: "s5", order: 5, title: "Specialize: Corporate / M&A / FinTech Law", description: "Join a top law firm or in-house legal team. Specialize in a high-value practice area.", type: "experience", duration: "Ongoing", certifications: ["LLM (optional)", "Specialized certifications"], skillsRequired: ["Corporate Law", "Contract Drafting", "Due Diligence", "Negotiation"], resources: ["AZB, Cyril Amarchand career portals", "LinkedIn", "LLM programs at NLUs"], status: "locked" },
    ],
  },
  {
    id: "rm-ias",
    careerId: "c-ias-officer",
    careerTitle: "IAS / Civil Services Officer",
    icon: "🏛️",
    applicableStages: ["afterGraduation"],
    totalSteps: 5,
    estimatedDuration: "2-4 years of preparation",
    steps: [
      { id: "s1", order: 1, title: "Complete Graduation", description: "Any graduation qualifies. Choose subjects aligned with UPSC optional paper.", type: "education", duration: "3-4 years", certifications: [], skillsRequired: ["Academic Knowledge", "Foundation in chosen optional"], resources: ["Any university curriculum"], status: "completed" },
      { id: "s2", order: 2, title: "UPSC Prelims Preparation", description: "Prepare GS Paper 1 (History, Geography, Polity, Economy, Science) and CSAT.", type: "skill", duration: "6-12 months", certifications: [], skillsRequired: ["Current Affairs", "Static GK", "CSAT", "Analytical Skills"], resources: ["NCERT books", "Vajiram & Ravi", "Drishti IAS", "The Hindu"], status: "current" },
      { id: "s3", order: 3, title: "Clear UPSC Prelims", description: "Appear and clear the UPSC Preliminary Examination (2 papers, MCQ).", type: "certification", duration: "1 attempt", certifications: ["Prelims Scorecard"], skillsRequired: ["Speed", "Accuracy", "Elimination Technique"], resources: ["UPSC previous papers", "InsightsIAS test series"], status: "locked" },
      { id: "s4", order: 4, title: "UPSC Mains (9 Papers)", description: "Write 9 papers including Essay, GS 1-4, and Optional papers.", type: "skill", duration: "4-5 months", certifications: [], skillsRequired: ["Answer Writing", "Essay", "Optional Subject Mastery"], resources: ["IASbaba", "ForumIAS", "Mrunal.org"], status: "locked" },
      { id: "s5", order: 5, title: "Personality Test (Interview) & Joining", description: "Appear for the UPSC Board interview and join LBSNAA for training.", type: "experience", duration: "2-3 months", certifications: ["IAS/IPS/IFS Appointment Order"], skillsRequired: ["Communication", "Leadership Outlook", "Current Affairs"], resources: ["Mock interview panels", "LBSNAA training curriculum"], status: "locked" },
    ],
  },
  {
    id: "rm-product-manager",
    careerId: "c-product-manager",
    careerTitle: "Product Manager",
    icon: "📱",
    applicableStages: ["afterGraduation", "workingProfessional"],
    totalSteps: 5,
    estimatedDuration: "1-2 years",
    steps: [
      { id: "s1", order: 1, title: "Understand Product Management Fundamentals", description: "Learn the PM role, product lifecycle, PRDs, user stories, and Agile methodology.", type: "skill", duration: "1 month", certifications: [], skillsRequired: ["Product Thinking", "User Stories", "Agile", "OKRs"], resources: ["Inspired by Marty Cagan", "Lenny's Newsletter", "ProductHunt", "Reforge"], status: "completed" },
      { id: "s2", order: 2, title: "Learn Analytics & Data Tools", description: "Become data-driven — learn SQL, Mixpanel/Amplitude, A/B testing, and funnel analysis.", type: "skill", duration: "2 months", certifications: ["Google Analytics Certification"], skillsRequired: ["SQL", "Product Analytics", "A/B Testing", "Funnel Analysis"], resources: ["Mode Analytics", "Amplitude Academy", "Kaggle SQL"], status: "current" },
      { id: "s3", order: 3, title: "Build Product Case Studies", description: "Solve product case studies — improve a product, enter new market, metrics decline.", type: "project", duration: "2 months", certifications: [], skillsRequired: ["Case Solving", "Product Metrics", "GTM Strategy"], resources: ["PM exercises", "ProductCase.io", "Exponent PM Prep"], status: "locked" },
      { id: "s4", order: 4, title: "Certifications & Portfolio", description: "Complete a PM certification and build a portfolio of product thinking documents.", type: "certification", duration: "2 months", certifications: ["Google PM Certificate", "Reforge PM Track"], skillsRequired: ["PRD Writing", "Strategy Docs", "Roadmapping"], resources: ["Coursera Google PM Cert", "Reforge", "Notion for portfolio"], status: "locked" },
      { id: "s5", order: 5, title: "PM Interview Prep & Landing Role", description: "Practice behavioral, product design, metrics, and execution interviews.", type: "experience", duration: "1-2 months", certifications: [], skillsRequired: ["PM Interviews", "STAR Method", "Case Interviews"], resources: ["Exponent", "Interviews.school", "Lewis C. Lin PM Interview"], status: "locked" },
    ],
  },
  {
    id: "rm-cybersecurity",
    careerId: "c-cybersecurity",
    careerTitle: "Cybersecurity Analyst",
    icon: "🛡️",
    applicableStages: ["after12th", "afterGraduation", "workingProfessional"],
    totalSteps: 6,
    estimatedDuration: "1.5-2 years",
    steps: [
      { id: "s1", order: 1, title: "Networking & OS Fundamentals", description: "Learn TCP/IP, DNS, HTTP, firewalls, Linux, and Windows security basics.", type: "skill", duration: "2 months", certifications: [], skillsRequired: ["Networking", "Linux", "TCP/IP", "Firewalls"], resources: ["Professor Messer", "TryHackMe Intro", "CompTIA Network+ study"], status: "completed" },
      { id: "s2", order: 2, title: "CompTIA Security+", description: "Get the industry-standard entry-level security certification.", type: "certification", duration: "2 months", certifications: ["CompTIA Security+"], skillsRequired: ["Threats & Vulnerabilities", "Cryptography", "Identity Management"], resources: ["Darril Gibson book", "Jason Dion practice tests", "Professor Messer"], status: "current" },
      { id: "s3", order: 3, title: "Ethical Hacking & Penetration Testing", description: "Learn offensive security — scanning, exploitation, and post-exploitation techniques.", type: "skill", duration: "3 months", certifications: [], skillsRequired: ["Nmap", "Metasploit", "Burp Suite", "OWASP Top 10"], resources: ["TryHackMe", "HackTheBox", "TCM Security"], status: "locked" },
      { id: "s4", order: 4, title: "CEH or OSCP Certification", description: "Earn a recognized ethical hacking certification.", type: "certification", duration: "3-6 months", certifications: ["CEH", "OSCP"], skillsRequired: ["Advanced Pentesting", "Report Writing", "CTF Skills"], resources: ["EC-Council CEH prep", "OffSec OSCP Training"], status: "locked" },
      { id: "s5", order: 5, title: "SOC Analysis & SIEM Tools", description: "Learn blue team skills — SIEM (Splunk), log analysis, incident response.", type: "skill", duration: "2 months", certifications: ["Splunk Core Certified User"], skillsRequired: ["SIEM", "Log Analysis", "Incident Response", "Threat Hunting"], resources: ["Splunk Training", "BTL1 Certification", "SANS Reading Room"], status: "locked" },
      { id: "s6", order: 6, title: "Bug Bounty & Real-World Practice", description: "Participate in bug bounty programs to find real vulnerabilities and build reputation.", type: "project", duration: "Ongoing", certifications: [], skillsRequired: ["Web App Security", "Bug Reporting", "Scope Understanding"], resources: ["HackerOne", "Bugcrowd", "OWASP Testing Guide"], status: "locked" },
    ],
  },
];
