import { College } from "../../app/knowNext/types";

export const COLLEGES: College[] = [
  {
    id: "col-iit-bombay",
    name: "Indian Institute of Technology Bombay",
    shortName: "IIT Bombay",
    location: "Mumbai, Maharashtra",
    state: "Maharashtra",
    type: "Government",
    ranking: 3,
    rating: 4.9,
    applicableStages: ["after12th", "afterGraduation"],
    coursesOffered: ["B.Tech CS", "B.Tech ECE", "B.Tech Mechanical", "B.Tech Civil", "M.Tech", "MBA", "PhD"],
    feeRange: { min: 200000, max: 250000 },
    placementAvgPackage: 21,
    placementTopPackage: 252,
    placementRate: 97,
    scholarshipsAvailable: true,
    scholarshipDetails: "Free tuition for family income < ₹5 LPA. Merit scholarships available.",
    admissionProcess: ["JEE Advanced rank", "JOSAA counselling", "Document verification"],
    entranceExamsAccepted: ["JEE Advanced"],
    overview: "IIT Bombay is India's premier engineering institute, consistently ranked among the top 200 universities globally. Known for exceptional research, innovation, and industry placements.",
    icon: "🏛️",
  },
  {
    id: "col-iit-delhi",
    name: "Indian Institute of Technology Delhi",
    shortName: "IIT Delhi",
    location: "New Delhi, Delhi",
    state: "Delhi",
    type: "Government",
    ranking: 2,
    rating: 4.9,
    applicableStages: ["after12th", "afterGraduation"],
    coursesOffered: ["B.Tech CS", "B.Tech ECE", "B.Tech Mechanical", "M.Tech", "MBA", "PhD"],
    feeRange: { min: 200000, max: 250000 },
    placementAvgPackage: 23,
    placementTopPackage: 300,
    placementRate: 98,
    scholarshipsAvailable: true,
    scholarshipDetails: "Full fee waiver for income below ₹5 LPA under SC/ST/OBC/EWS categories.",
    admissionProcess: ["JEE Advanced rank", "JOSAA counselling", "Institute reporting"],
    entranceExamsAccepted: ["JEE Advanced"],
    overview: "India's top-ranked institution with world-class faculty, research output, and startup ecosystem. Alumni include CEOs of global companies.",
    icon: "🏛️",
  },
  {
    id: "col-iim-ahmedabad",
    name: "Indian Institute of Management Ahmedabad",
    shortName: "IIM Ahmedabad",
    location: "Ahmedabad, Gujarat",
    state: "Gujarat",
    type: "Government",
    ranking: 1,
    rating: 5.0,
    applicableStages: ["afterGraduation", "workingProfessional"],
    coursesOffered: ["MBA (PGP)", "Executive MBA (PGPX)", "PhD", "FPM"],
    feeRange: { min: 2400000, max: 2700000 },
    placementAvgPackage: 35,
    placementTopPackage: 180,
    placementRate: 100,
    scholarshipsAvailable: true,
    scholarshipDetails: "Need-based scholarships, MeritCum-Need awards. No student denied due to financial constraints.",
    admissionProcess: ["CAT exam", "Shortlisting", "Written Ability Test", "Personal Interview"],
    entranceExamsAccepted: ["CAT", "GMAT (for international)"],
    overview: "Asia's #1 business school. PGP graduates are among the most sought-after by top consulting firms, investment banks, and global MNCs.",
    icon: "🏢",
  },
  {
    id: "col-aiims-delhi",
    name: "All India Institute of Medical Sciences",
    shortName: "AIIMS Delhi",
    location: "New Delhi, Delhi",
    state: "Delhi",
    type: "Government",
    ranking: 1,
    rating: 5.0,
    applicableStages: ["after12th"],
    coursesOffered: ["MBBS", "MD", "MS", "M.Sc", "PhD", "Nursing"],
    feeRange: { min: 1000, max: 1000 },
    placementAvgPackage: 10,
    placementTopPackage: 80,
    placementRate: 100,
    scholarshipsAvailable: true,
    scholarshipDetails: "One of the cheapest medical educations in the world at ~₹1,000/year. Hostel and mess subsidized.",
    admissionProcess: ["NEET scorecard", "Merit-based rank", "AIIMS counselling"],
    entranceExamsAccepted: ["NEET"],
    overview: "India's #1 medical institution. Admission through NEET. AIIMS graduates are highly respected globally and can pursue residencies in the USA, UK, and Canada.",
    icon: "🏥",
  },
  {
    id: "col-nlu-delhi",
    name: "National Law University Delhi",
    shortName: "NLU Delhi",
    location: "New Delhi, Delhi",
    state: "Delhi",
    type: "Government",
    ranking: 1,
    rating: 4.8,
    applicableStages: ["after12th", "afterGraduation"],
    coursesOffered: ["BA LLB (Hons)", "LLM", "PhD"],
    feeRange: { min: 250000, max: 300000 },
    placementAvgPackage: 20,
    placementTopPackage: 85,
    placementRate: 95,
    scholarshipsAvailable: true,
    scholarshipDetails: "Need-cum-merit scholarships. SC/ST fee exemptions available.",
    admissionProcess: ["AILET entrance exam", "Merit list", "Document verification"],
    entranceExamsAccepted: ["AILET", "CLAT"],
    overview: "India's top law school for those aspiring to corporate law. Graduates join top firms like AZB, Cyril Amarchand, and Khaitan & Co.",
    icon: "⚖️",
  },
  {
    id: "col-bits-pilani",
    name: "BITS Pilani",
    shortName: "BITS Pilani",
    location: "Pilani, Rajasthan",
    state: "Rajasthan",
    type: "Deemed",
    ranking: 6,
    rating: 4.7,
    applicableStages: ["after12th", "afterGraduation"],
    coursesOffered: ["B.Tech CS", "B.Tech ECE", "B.Tech EE", "B.Tech Chemical", "B.Pharm", "M.Tech", "MBA"],
    feeRange: { min: 500000, max: 600000 },
    placementAvgPackage: 18,
    placementTopPackage: 120,
    placementRate: 94,
    scholarshipsAvailable: true,
    scholarshipDetails: "Merit scholarships for top BITSAT performers. Need-based assistance available.",
    admissionProcess: ["BITSAT score", "Merit list", "Online seat allotment"],
    entranceExamsAccepted: ["BITSAT"],
    overview: "One of India's top private engineering universities with a unique dual-degree program and excellent industry connections through the BITS Practice School.",
    icon: "🎓",
  },
  {
    id: "col-symbiosis-law",
    name: "Symbiosis Law School Pune",
    shortName: "SLS Pune",
    location: "Pune, Maharashtra",
    state: "Maharashtra",
    type: "Deemed",
    ranking: 5,
    rating: 4.4,
    applicableStages: ["after12th", "afterGraduation"],
    coursesOffered: ["BA LLB", "BBA LLB", "LLM", "PhD"],
    feeRange: { min: 350000, max: 450000 },
    placementAvgPackage: 12,
    placementTopPackage: 50,
    placementRate: 88,
    scholarshipsAvailable: true,
    scholarshipDetails: "Merit scholarships for SLAT top performers. SC/ST fee concessions.",
    admissionProcess: ["SLAT (Symbiosis Law Admission Test)", "Personal Interaction", "Writing Ability Test"],
    entranceExamsAccepted: ["CLAT", "SLAT"],
    overview: "A leading private law school known for its strong corporate law placements and moot court culture.",
    icon: "⚖️",
  },
  {
    id: "col-nit-trichy",
    name: "National Institute of Technology Tiruchirappalli",
    shortName: "NIT Trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    state: "Tamil Nadu",
    type: "Government",
    ranking: 8,
    rating: 4.6,
    applicableStages: ["after12th", "afterGraduation"],
    coursesOffered: ["B.Tech CS", "B.Tech ECE", "B.Tech Mechanical", "B.Tech Civil", "B.Tech Chemical", "M.Tech", "MBA", "PhD"],
    feeRange: { min: 130000, max: 160000 },
    placementAvgPackage: 14,
    placementTopPackage: 80,
    placementRate: 93,
    scholarshipsAvailable: true,
    scholarshipDetails: "SC/ST scholarship from MHRD. Merit-cum-means scholarship for economically weaker sections.",
    admissionProcess: ["JEE Main rank", "JoSAA counselling", "Home state quota"],
    entranceExamsAccepted: ["JEE Main"],
    overview: "Best NIT in India by several rankings. Strong industry connections in Tamil Nadu's manufacturing and IT hubs.",
    icon: "🏫",
  },
  {
    id: "col-du-srcc",
    name: "Shri Ram College of Commerce, Delhi University",
    shortName: "SRCC Delhi",
    location: "New Delhi, Delhi",
    state: "Delhi",
    type: "Government",
    ranking: 1,
    rating: 4.7,
    applicableStages: ["after12th", "afterGraduation"],
    coursesOffered: ["B.Com (Hons)", "BA Economics (Hons)", "M.Com", "MBA"],
    feeRange: { min: 20000, max: 25000 },
    placementAvgPackage: 14,
    placementTopPackage: 60,
    placementRate: 92,
    scholarshipsAvailable: true,
    scholarshipDetails: "DU merit scholarship. SC/ST concessions. Private scholarships from alumni network.",
    admissionProcess: ["CUET score", "Merit list", "DU counselling"],
    entranceExamsAccepted: ["CUET"],
    overview: "India's most prestigious commerce college. Alumni include top bankers, CA partners, and finance ministers.",
    icon: "📊",
  },
  {
    id: "col-iit-madras",
    name: "Indian Institute of Technology Madras",
    shortName: "IIT Madras",
    location: "Chennai, Tamil Nadu",
    state: "Tamil Nadu",
    type: "Government",
    ranking: 1,
    rating: 5.0,
    applicableStages: ["after12th", "afterGraduation"],
    coursesOffered: ["B.Tech CS", "B.Tech ECE", "B.Tech Aerospace", "B.Tech Ocean Engg", "M.Tech", "PhD", "BS Data Science (Online)"],
    feeRange: { min: 200000, max: 250000 },
    placementAvgPackage: 22,
    placementTopPackage: 252,
    placementRate: 98,
    scholarshipsAvailable: true,
    scholarshipDetails: "Full fee waiver for family income < ₹5 LPA. Merit scholarships for top 10% students.",
    admissionProcess: ["JEE Advanced rank", "JoSAA / CSAB counselling"],
    entranceExamsAccepted: ["JEE Advanced", "GATE (for PG)"],
    overview: "NIRF #1 engineering institute in India. Strong in AI, quantum computing, ocean engineering, and aerospace. Has a thriving startup ecosystem.",
    icon: "🏛️",
  },
  {
    id: "col-nid-ahmedabad",
    name: "National Institute of Design",
    shortName: "NID Ahmedabad",
    location: "Ahmedabad, Gujarat",
    state: "Gujarat",
    type: "Government",
    ranking: 1,
    rating: 4.8,
    applicableStages: ["after12th", "afterGraduation"],
    coursesOffered: ["B.Des (Product, Communication, Textile, Furniture)", "M.Des", "PhD"],
    feeRange: { min: 180000, max: 220000 },
    placementAvgPackage: 12,
    placementTopPackage: 50,
    placementRate: 90,
    scholarshipsAvailable: true,
    scholarshipDetails: "Government scholarships for SC/ST/OBC. Partial scholarships for merit.",
    admissionProcess: ["NID DAT (Design Aptitude Test)", "Studio Test", "Personal Interview"],
    entranceExamsAccepted: ["NID DAT"],
    overview: "India's #1 design school, globally recognized. Alumni work at Apple, Google, IDEO, and leading Indian design studios.",
    icon: "🎨",
  },
  {
    id: "col-iisc-bangalore",
    name: "Indian Institute of Science",
    shortName: "IISc Bangalore",
    location: "Bangalore, Karnataka",
    state: "Karnataka",
    type: "Government",
    ranking: 1,
    rating: 5.0,
    applicableStages: ["afterGraduation", "workingProfessional"],
    coursesOffered: ["B.S. Research", "M.Tech", "M.Des", "M.Mgt", "PhD"],
    feeRange: { min: 30000, max: 90000 },
    placementAvgPackage: 20,
    placementTopPackage: 80,
    placementRate: 85,
    scholarshipsAvailable: true,
    scholarshipDetails: "CSIR/UGC fellowships. JRF/SRF for research scholars. MHRD scholarships.",
    admissionProcess: ["GATE score", "JAM (for B.S.)", "Written test + Interview for PhD"],
    entranceExamsAccepted: ["GATE", "JAM", "JEST"],
    overview: "India's top research institution, globally ranked #1 in citations per paper. The destination for serious researchers and scientists.",
    icon: "🔬",
  },
  {
    id: "col-iim-bangalore",
    name: "Indian Institute of Management Bangalore",
    shortName: "IIM Bangalore",
    location: "Bangalore, Karnataka",
    state: "Karnataka",
    type: "Government",
    ranking: 2,
    rating: 4.9,
    applicableStages: ["afterGraduation", "workingProfessional"],
    coursesOffered: ["MBA (PGP)", "Executive MBA (EPGP)", "PGPBA", "PhD"],
    feeRange: { min: 2400000, max: 2700000 },
    placementAvgPackage: 33,
    placementTopPackage: 150,
    placementRate: 100,
    scholarshipsAvailable: true,
    scholarshipDetails: "Need-based scholarships funded by industry donors. Full fellowship for PhD students.",
    admissionProcess: ["CAT score", "Shortlisting by percentile", "WAT + PI"],
    entranceExamsAccepted: ["CAT", "GMAT"],
    overview: "India's #2 business school with exceptional placement in consulting, finance, and tech. Located in India's startup capital — Bangalore.",
    icon: "🏢",
  },
  {
    id: "col-iimc",
    name: "Indian Institute of Mass Communication",
    shortName: "IIMC Delhi",
    location: "New Delhi, Delhi",
    state: "Delhi",
    type: "Government",
    ranking: 1,
    rating: 4.5,
    applicableStages: ["after12th", "afterGraduation"],
    coursesOffered: ["PG Diploma in Journalism", "PG Diploma in Advertising", "PG Diploma in Radio & TV", "MA Mass Communication"],
    feeRange: { min: 80000, max: 150000 },
    placementAvgPackage: 8,
    placementTopPackage: 30,
    placementRate: 85,
    scholarshipsAvailable: true,
    scholarshipDetails: "Government merit scholarships. OBC/SC/ST fee concessions.",
    admissionProcess: ["IIMC Entrance Exam", "Interview", "Portfolio submission"],
    entranceExamsAccepted: ["IIMC Entrance"],
    overview: "India's premier mass communication institute. Alumni lead India's top media organizations — NDTV, Times Group, The Hindu.",
    icon: "📰",
  },
  {
    id: "col-xlri",
    name: "XLRI Xavier School of Management",
    shortName: "XLRI Jamshedpur",
    location: "Jamshedpur, Jharkhand",
    state: "Jharkhand",
    type: "Autonomous",
    ranking: 5,
    rating: 4.7,
    applicableStages: ["afterGraduation", "workingProfessional"],
    coursesOffered: ["MBA (BM)", "MBA (HRM)", "GMP (1-year)", "PhD"],
    feeRange: { min: 2200000, max: 2500000 },
    placementAvgPackage: 30,
    placementTopPackage: 120,
    placementRate: 100,
    scholarshipsAvailable: true,
    scholarshipDetails: "Need-based scholarships funded by alumni network and corporate donors.",
    admissionProcess: ["XAT score", "Shortlisting", "GD/PI"],
    entranceExamsAccepted: ["XAT", "GMAT"],
    overview: "One of India's finest B-schools, especially known for HR management. Consistently in top 5 for HR specialization.",
    icon: "🏢",
  },
  {
    id: "col-iit-kharagpur",
    name: "Indian Institute of Technology Kharagpur",
    shortName: "IIT Kharagpur",
    location: "Kharagpur, West Bengal",
    state: "West Bengal",
    type: "Government",
    ranking: 5,
    rating: 4.8,
    applicableStages: ["after12th", "afterGraduation"],
    coursesOffered: ["B.Tech CS", "B.Tech EE", "B.Tech Mechanical", "B.Tech Civil", "Architecture", "Law", "MBA", "M.Tech", "PhD"],
    feeRange: { min: 200000, max: 250000 },
    placementAvgPackage: 20,
    placementTopPackage: 300,
    placementRate: 96,
    scholarshipsAvailable: true,
    scholarshipDetails: "Merit-cum-means scholarship for family income < ₹5 LPA. Several alumni-funded scholarships.",
    admissionProcess: ["JEE Advanced rank", "JoSAA counselling"],
    entranceExamsAccepted: ["JEE Advanced"],
    overview: "The oldest IIT, largest by campus, and one of the most diverse. Offers rare disciplines like Architecture, Law, and Management alongside engineering.",
    icon: "🏛️",
  },
  {
    id: "col-manipal",
    name: "Manipal Academy of Higher Education",
    shortName: "MAHE Manipal",
    location: "Manipal, Karnataka",
    state: "Karnataka",
    type: "Deemed",
    ranking: 7,
    rating: 4.4,
    applicableStages: ["after12th", "afterGraduation"],
    coursesOffered: ["MBBS", "B.Tech CS", "B.Tech ECE", "B.Pharm", "B.Arch", "BA", "MBA"],
    feeRange: { min: 400000, max: 1500000 },
    placementAvgPackage: 12,
    placementTopPackage: 60,
    placementRate: 88,
    scholarshipsAvailable: true,
    scholarshipDetails: "Merit scholarship for top MET scorers. Special scholarships for Karnataka students.",
    admissionProcess: ["MET (Manipal Entrance Test)", "JEE/NEET scores", "Merit list"],
    entranceExamsAccepted: ["MET", "JEE Main", "NEET"],
    overview: "One of India's top private universities offering world-class infrastructure, 400+ programs, and a strong global alumni network.",
    icon: "🎓",
  },
  {
    id: "col-christ-bangalore",
    name: "CHRIST (Deemed to be University)",
    shortName: "CHRIST Bangalore",
    location: "Bangalore, Karnataka",
    state: "Karnataka",
    type: "Deemed",
    ranking: 12,
    rating: 4.3,
    applicableStages: ["after12th", "afterGraduation"],
    coursesOffered: ["BA Psychology", "B.Com", "BBA", "MBA", "M.Sc", "B.Sc CS", "BJMC"],
    feeRange: { min: 120000, max: 250000 },
    placementAvgPackage: 8,
    placementTopPackage: 35,
    placementRate: 82,
    scholarshipsAvailable: true,
    scholarshipDetails: "Merit scholarships for 10+2 toppers. Need-based fee concessions available.",
    admissionProcess: ["CHRIST Entrance Test", "Personal Interview", "Document verification"],
    entranceExamsAccepted: ["CUET", "CHRIST Entrance"],
    overview: "A holistic university known for psychology, journalism, and commerce programs. Strong focus on liberal arts and extracurricular development.",
    icon: "🏫",
  },
  {
    id: "col-vit",
    name: "Vellore Institute of Technology",
    shortName: "VIT Vellore",
    location: "Vellore, Tamil Nadu",
    state: "Tamil Nadu",
    type: "Deemed",
    ranking: 10,
    rating: 4.2,
    applicableStages: ["after12th"],
    coursesOffered: ["B.Tech CS", "B.Tech ECE", "B.Tech Mechanical", "B.Tech Biotech", "MBA", "M.Tech"],
    feeRange: { min: 200000, max: 250000 },
    placementAvgPackage: 10,
    placementTopPackage: 45,
    placementRate: 85,
    scholarshipsAvailable: true,
    scholarshipDetails: "Merit scholarship for VITEEE top ranks. Special scholarship for economically weaker sections.",
    admissionProcess: ["VITEEE score", "Merit list", "Online counselling"],
    entranceExamsAccepted: ["VITEEE", "JEE Main"],
    overview: "One of India's largest private engineering universities with strong IT industry connections and a massive campus.",
    icon: "🏫",
  },
  {
    id: "col-tiss",
    name: "Tata Institute of Social Sciences",
    shortName: "TISS Mumbai",
    location: "Mumbai, Maharashtra",
    state: "Maharashtra",
    type: "Deemed",
    ranking: 1,
    rating: 4.7,
    applicableStages: ["afterGraduation", "workingProfessional"],
    coursesOffered: ["MA Social Work", "MA HRM & LR", "MA Education", "MA Public Health", "MA Media Studies", "PhD"],
    feeRange: { min: 15000, max: 80000 },
    placementAvgPackage: 12,
    placementTopPackage: 45,
    placementRate: 90,
    scholarshipsAvailable: true,
    scholarshipDetails: "Multiple government scholarships. Low fee structure with hostel facility.",
    admissionProcess: ["TISS NET (National Entrance Test)", "Pre-Interview Test", "Personal Interview"],
    entranceExamsAccepted: ["TISS NET"],
    overview: "India's premier social science institution. The go-to institute for HR management, social work, public policy, and media studies.",
    icon: "🏫",
  },
];
