import { Scholarship } from "../../app/knowNext/types";

export const SCHOLARSHIPS: Scholarship[] = [
  {
    id: "sch-pm-scholarship",
    name: "Prime Minister's Scholarship Scheme",
    provider: "Ministry of Home Affairs, Govt. of India",
    amount: 36000,
    frequency: "Annual",
    eligibility: ["Ward/widow of Ex-Servicemen or Ex-Coast Guard personnel", "Minimum 60% marks in qualifying exam", "First year of graduate/postgraduate course"],
    applicableStages: ["after12th", "afterGraduation"],
    requiredDocuments: ["Service certificate of parent", "Mark sheets", "Aadhar card", "Bank account details", "Income certificate"],
    deadline: "2025-10-31",
    applicationUrl: "https://ksb.gov.in/pm-scholarship.htm",
    category: "Category",
  },
  {
    id: "sch-inspire",
    name: "INSPIRE Scholarship (SHE)",
    provider: "Department of Science & Technology, Govt. of India",
    amount: 80000,
    frequency: "Annual",
    eligibility: ["Top 1% in class 12 board exams", "Enrolled in Natural/Basic Sciences (B.Sc/BS/Int. M.Sc)", "Age below 22 years"],
    applicableStages: ["after12th"],
    requiredDocuments: ["12th mark sheet", "Board topper certificate", "College admission letter", "Aadhar card", "Bank passbook"],
    deadline: "2025-09-30",
    applicationUrl: "https://online-inspire.gov.in",
    category: "Merit",
  },
  {
    id: "sch-central-sector",
    name: "Central Sector Scholarship",
    provider: "Ministry of Education, Govt. of India",
    amount: 12000,
    frequency: "Annual",
    eligibility: ["Top 20 percentile in Class 12 board exams", "Family income below ₹8 LPA", "Regular student in a recognized college/university"],
    applicableStages: ["after12th"],
    requiredDocuments: ["Class 12 marksheet", "Domicile certificate", "Income certificate", "Bank details", "Institution certificate"],
    deadline: "2025-11-30",
    applicationUrl: "https://scholarships.gov.in",
    category: "Merit",
  },
  {
    id: "sch-hdfc-badhte",
    name: "HDFC Bank Parivartan's ECSS Scholarship",
    provider: "HDFC Bank",
    amount: 75000,
    frequency: "Annual",
    eligibility: ["Pursuing professional courses (Engineering, Medical, Law, MBA)", "Family income below ₹5 LPA", "Minimum 55% marks in previous qualifying exam"],
    applicableStages: ["after12th", "afterGraduation"],
    requiredDocuments: ["Income certificate", "Mark sheets", "College fee receipt", "Bank account details", "Photo ID"],
    deadline: "2025-07-31",
    applicationUrl: "https://www.hdfcbank.com/parivartan-scholarships",
    category: "Need-based",
  },
  {
    id: "sch-jn-tata",
    name: "JN Tata Endowment Scholarship",
    provider: "JN Tata Endowment",
    amount: 500000,
    frequency: "One-time",
    eligibility: ["Indian national planning to pursue higher education abroad", "First-class academic record", "Under 45 years of age"],
    applicableStages: ["afterGraduation", "workingProfessional"],
    requiredDocuments: ["Academic transcripts", "Proof of admission to foreign university", "References from professors", "Research proposal (for PhD)"],
    deadline: "2025-12-31",
    applicationUrl: "https://jntataendowment.org",
    category: "Merit",
  },
  {
    id: "sch-nsp-post",
    name: "Post-Matric Scholarship (SC Students)",
    provider: "Ministry of Social Justice & Empowerment, Govt. of India",
    amount: 12000,
    frequency: "Annual",
    eligibility: ["Scheduled Caste (SC) student", "Family income below ₹2.5 LPA", "Studying in Post-Matric or Post-Secondary course"],
    applicableStages: ["after10th", "after12th", "afterGraduation"],
    requiredDocuments: ["SC certificate", "Income certificate", "Previous year mark sheet", "Bank account", "Aadhar card"],
    deadline: "2025-10-15",
    applicationUrl: "https://scholarships.gov.in",
    category: "Category",
  },
  {
    id: "sch-sitaram-jindal",
    name: "Sitaram Jindal Foundation Scholarship",
    provider: "Sitaram Jindal Foundation",
    amount: 24000,
    frequency: "Annual",
    eligibility: ["Family income below ₹2 LPA", "Minimum 60% marks", "Studying in government or government-aided institution"],
    applicableStages: ["after10th", "after12th", "afterGraduation"],
    requiredDocuments: ["Income certificate", "Mark sheets", "College fee receipt", "BPL card (if applicable)", "Bank details"],
    deadline: "2025-08-31",
    applicationUrl: "https://sitaramjindalfoundation.org",
    category: "Need-based",
  },
  {
    id: "sch-colgate-palmolive",
    name: "Colgate Keep India Smiling Scholarship",
    provider: "Colgate Palmolive India",
    amount: 30000,
    frequency: "Annual",
    eligibility: ["10+2 passed with minimum 75% marks", "Enrolled in undergraduate program", "Family income below ₹5 LPA"],
    applicableStages: ["after12th"],
    requiredDocuments: ["12th mark sheet", "Family income certificate", "College admission letter", "Photo ID", "Bank details"],
    deadline: "2025-08-15",
    applicationUrl: "https://buddy4study.com/colgate",
    category: "Need-based",
  },
  {
    id: "sch-aicte-pragati",
    name: "AICTE Pragati Scholarship for Girls",
    provider: "AICTE (All India Council for Technical Education)",
    amount: 50000,
    frequency: "Annual",
    eligibility: ["Female student", "First year of AICTE-approved degree/diploma program", "Family income below ₹8 LPA", "One scholarship per family"],
    applicableStages: ["after12th"],
    requiredDocuments: ["12th marksheet", "College admission letter", "Income certificate", "Bank account (Aadhar-linked)", "Family member certificate"],
    deadline: "2025-11-15",
    applicationUrl: "https://scholarships.gov.in",
    category: "Category",
  },
  {
    id: "sch-dr-reddy",
    name: "Dr. Reddy's Foundation SAKSHAM Scholarship",
    provider: "Dr. Reddy's Laboratories Foundation",
    amount: 40000,
    frequency: "Annual",
    eligibility: ["Students from lower-income backgrounds (< ₹3 LPA)", "Pursuing vocational education or undergraduate programs", "Age between 18-25 years"],
    applicableStages: ["after10th", "after12th"],
    requiredDocuments: ["Income certificate", "Enrollment proof", "Aadhar card", "Recent photograph", "Bank account details"],
    deadline: "2025-09-15",
    applicationUrl: "https://www.drreddys.com/foundation",
    category: "Need-based",
  },
  {
    id: "sch-national-means",
    name: "National Means Cum Merit Scholarship",
    provider: "Ministry of Education, Govt. of India",
    amount: 12000,
    frequency: "Annual",
    eligibility: ["Studying in Class 9 onwards", "Family income below ₹1.5 LPA", "Pass NMMS examination in Class 8"],
    applicableStages: ["after10th"],
    requiredDocuments: ["NMMS exam scorecard", "Income certificate", "Mark sheets", "Bank account", "Aadhar"],
    deadline: "2025-12-31",
    applicationUrl: "https://scholarships.gov.in/nmms",
    category: "Merit",
  },
  {
    id: "sch-iocl-merit",
    name: "IOCL Scholarship for Engineering/MBA Students",
    provider: "Indian Oil Corporation Limited (IOCL)",
    amount: 30000,
    frequency: "Annual",
    eligibility: ["Enrolled in B.Tech/MBBS/MBA from a recognized institution", "Family income below ₹5 LPA", "Minimum 60% in 12th standard"],
    applicableStages: ["after12th", "afterGraduation"],
    requiredDocuments: ["12th and previous semester marksheets", "Income certificate", "College fee receipt", "Aadhar card", "Bank details"],
    deadline: "2025-10-01",
    applicationUrl: "https://iocl.com/Scholarship",
    category: "Need-based",
  },
  {
    id: "sch-kishore-vaigyanik",
    name: "Kishore Vaigyanik Protsahan Yojana (KVPY)",
    provider: "Indian Institute of Science (IISc), funded by DST",
    amount: 96000,
    frequency: "Annual",
    eligibility: ["Studying in Class 11/12 or first year of UG in basic sciences", "Indian national", "Strong aptitude for science research"],
    applicableStages: ["after10th", "after12th"],
    requiredDocuments: ["Marksheets", "School/college enrollment proof", "Category certificate (if applicable)", "Bank details", "Aadhar"],
    deadline: "2025-09-01",
    applicationUrl: "https://kvpy.iisc.ac.in",
    category: "Merit",
  },
  {
    id: "sch-google-anita-borg",
    name: "Google Women Techmakers Scholarship",
    provider: "Google",
    amount: 100000,
    frequency: "One-time",
    eligibility: ["Female student", "Studying Computer Science, Engineering, or related technical field", "Enrolled full-time in bachelor's or master's program"],
    applicableStages: ["afterGraduation"],
    requiredDocuments: ["Academic transcripts", "Resume/CV", "Essay responses", "Letter of recommendation", "College enrollment proof"],
    deadline: "2025-12-01",
    applicationUrl: "https://buildyourfuture.withgoogle.com/scholarships",
    category: "Category",
  },
  {
    id: "sch-oasis",
    name: "OASIS Scholarship (West Bengal OBC)",
    provider: "West Bengal Backward Classes Welfare Department",
    amount: 12000,
    frequency: "Annual",
    eligibility: ["OBC (Non-Creamy Layer) student from West Bengal", "Studying in a recognized institution", "Family income below ₹2.5 LPA"],
    applicableStages: ["after10th", "after12th", "afterGraduation"],
    requiredDocuments: ["OBC certificate", "Income certificate", "Domicile (WB)", "Mark sheets", "Bank account details"],
    deadline: "2025-11-30",
    applicationUrl: "https://oasis.gov.in",
    category: "Category",
  },
];
