import { Career } from "../../app/knowNext/types";

export const CAREERS: Career[] = [
  // ── Technology ──────────────────────────────────────────────────────────────
  {
    id: "c-data-scientist",
    title: "Data Scientist",
    category: "Technology",
    industry: "Technology / AI",
    icon: "🧬",
    tagline: "Turn data into decisions that drive businesses forward",
    overview:
      "Data Scientists collect, analyze, and interpret large datasets to uncover trends and build predictive models that help organizations make data-driven decisions. They work at the intersection of statistics, programming, and domain expertise.",
    applicableStages: ["afterGraduation", "workingProfessional"],
    requiredSkills: ["Python", "Statistics", "Machine Learning", "SQL", "Data Visualization", "Deep Learning"],
    educationalPath: [
      { level: "10+2 (PCM/PCB)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "B.Tech CS / B.Sc Statistics / B.Sc Math", duration: "3-4 years", institutions: ["IITs", "NITs", "State universities"] },
      { level: "M.Tech AI/DS or MBA (Analytics)", duration: "2 years", institutions: ["IISc", "IITs", "BITS"] },
    ],
    entranceExams: ["JEE", "GATE", "CUET"],
    certifications: ["Google Data Analytics", "IBM Data Science", "Coursera ML Specialization"],
    topRecruiters: ["Google", "Amazon", "Microsoft", "Flipkart", "Paytm", "Infosys", "TCS"],
    futureScope: "AI and ML adoption across every industry makes Data Scientists one of the most in-demand roles globally. By 2030, India is expected to have 11 million unfilled data science roles.",
    industryDemand: "Very High",
    salaryRange: { min: 8, max: 40 },
    jobRoles: ["Data Analyst", "ML Engineer", "Research Scientist", "AI Product Manager", "BI Developer"],
    growthOpportunities: ["Lead Data Scientist", "Chief Data Officer", "AI Research Lead", "Entrepreneur"],
    avgSalary: 18,
    educationYears: 6,
    growthPercent: 35,
  },
  {
    id: "c-ai-engineer",
    title: "AI Engineer",
    category: "Technology",
    industry: "Technology / AI",
    icon: "🤖",
    tagline: "Build intelligent systems that learn, adapt, and solve real problems",
    overview:
      "AI Engineers design and deploy production-grade artificial intelligence systems. They bridge the gap between research and real-world AI products, building everything from recommendation engines to autonomous systems.",
    applicableStages: ["afterGraduation", "workingProfessional"],
    requiredSkills: ["Python", "Deep Learning", "TensorFlow/PyTorch", "Cloud (AWS/GCP)", "MLOps", "NLP"],
    educationalPath: [
      { level: "10+2 (PCM)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "B.Tech CS / ECE", duration: "4 years", institutions: ["IITs", "NITs", "BITS"] },
      { level: "M.Tech AI or MS (Research)", duration: "2 years", institutions: ["IISc", "IITs", "International universities"] },
    ],
    entranceExams: ["JEE", "GATE"],
    certifications: ["TensorFlow Developer", "AWS Machine Learning Specialty", "Deep Learning Specialization (Coursera)"],
    topRecruiters: ["OpenAI", "Google DeepMind", "Microsoft", "NVIDIA", "Anthropic", "Meta AI"],
    futureScope: "Generative AI alone is projected to create 97 million new roles globally. AI Engineers are at the center of this transformation, with salaries among the highest in tech.",
    industryDemand: "Very High",
    salaryRange: { min: 12, max: 60 },
    jobRoles: ["ML Engineer", "AI Research Scientist", "NLP Engineer", "Computer Vision Engineer", "AI Product Lead"],
    growthOpportunities: ["Principal AI Scientist", "Head of AI", "CTO at AI Startup", "AI Researcher"],
    avgSalary: 22,
    educationYears: 6,
    growthPercent: 40,
  },
  {
    id: "c-software-engineer",
    title: "Software Engineer",
    category: "Technology",
    industry: "Technology",
    icon: "💻",
    tagline: "Write code that powers apps, platforms, and digital experiences",
    overview:
      "Software Engineers design, develop, test, and maintain software systems. From mobile apps to large-scale backend platforms, they are the builders of the digital world.",
    applicableStages: ["after12th", "afterGraduation", "workingProfessional"],
    requiredSkills: ["DSA", "Java/Python/JavaScript", "React/Node.js", "Databases", "System Design", "Git"],
    educationalPath: [
      { level: "10+2 (PCM)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "B.Tech CS / BCA", duration: "3-4 years", institutions: ["IITs", "NITs", "Private engineering colleges"] },
    ],
    entranceExams: ["JEE", "CUET"],
    certifications: ["AWS Developer", "Oracle Java", "Full Stack Web Development (Meta)"],
    topRecruiters: ["Google", "Microsoft", "Amazon", "Infosys", "Wipro", "TCS", "Zoho", "Razorpay"],
    futureScope: "Software engineering remains among the most stable and growing careers globally, with constant demand across all industries — from healthcare to finance to government.",
    industryDemand: "High",
    salaryRange: { min: 4, max: 50 },
    jobRoles: ["Frontend Developer", "Backend Engineer", "Full Stack Developer", "DevOps Engineer", "Cloud Engineer"],
    growthOpportunities: ["Senior Engineer", "Tech Lead", "Engineering Manager", "CTO", "Tech Entrepreneur"],
    avgSalary: 12,
    educationYears: 4,
    growthPercent: 22,
  },
  {
    id: "c-cybersecurity",
    title: "Cybersecurity Analyst",
    category: "Technology",
    industry: "Technology / Security",
    icon: "🛡️",
    tagline: "Protect organizations from digital threats and cyber attacks",
    overview:
      "Cybersecurity Analysts safeguard computer systems and networks from threats, breaches, and attacks. With cyber threats growing exponentially, this field offers exceptional job security and growth.",
    applicableStages: ["after12th", "afterGraduation", "workingProfessional"],
    requiredSkills: ["Network Security", "Ethical Hacking", "SIEM Tools", "Python", "Cryptography", "Risk Assessment"],
    educationalPath: [
      { level: "10+2 (PCM)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "B.Tech CS / BCA / B.Sc IT", duration: "3-4 years", institutions: ["NITs", "Private colleges"] },
    ],
    entranceExams: ["JEE", "CUET"],
    certifications: ["CEH (Certified Ethical Hacker)", "CISSP", "CompTIA Security+", "OSCP"],
    topRecruiters: ["DRDO", "ISRO", "IBM", "Deloitte", "PwC", "Palo Alto Networks", "Check Point"],
    futureScope: "Cybercrime damages are projected to exceed $10.5 trillion annually by 2025, making cybersecurity professionals indispensable.",
    industryDemand: "Very High",
    salaryRange: { min: 6, max: 35 },
    jobRoles: ["Security Analyst", "Penetration Tester", "SOC Engineer", "CISO", "Forensic Analyst"],
    growthOpportunities: ["Chief Information Security Officer", "Security Consultant", "Red Team Lead"],
    avgSalary: 14,
    educationYears: 4,
    growthPercent: 30,
  },
  {
    id: "c-cloud-architect",
    title: "Cloud Architect",
    category: "Technology",
    industry: "Technology / Cloud",
    icon: "☁️",
    tagline: "Design scalable cloud infrastructure for modern businesses",
    overview:
      "Cloud Architects design and oversee cloud computing strategies, including cloud adoption plans, cloud application design, and cloud management and monitoring.",
    applicableStages: ["afterGraduation", "workingProfessional"],
    requiredSkills: ["AWS/Azure/GCP", "Kubernetes", "Terraform", "Networking", "Security", "CI/CD"],
    educationalPath: [
      { level: "10+2 (PCM)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "B.Tech CS / ECE", duration: "4 years", institutions: ["IITs", "NITs"] },
    ],
    entranceExams: ["JEE", "GATE"],
    certifications: ["AWS Solutions Architect", "GCP Professional Architect", "Azure Solutions Architect Expert"],
    topRecruiters: ["Amazon", "Microsoft", "Google", "Accenture", "IBM", "Capgemini"],
    futureScope: "Cloud market is expected to grow to $1 trillion by 2028. Cloud architects are among the highest-paid IT professionals.",
    industryDemand: "Very High",
    salaryRange: { min: 15, max: 60 },
    jobRoles: ["Cloud Engineer", "Solutions Architect", "DevOps Lead", "Cloud Consultant", "Platform Engineer"],
    growthOpportunities: ["Principal Architect", "VP Engineering", "Cloud CoE Lead", "CTO"],
    avgSalary: 25,
    educationYears: 4,
    growthPercent: 28,
  },

  // ── Healthcare ────────────────────────────────────────────────────────────
  {
    id: "c-doctor",
    title: "Medical Doctor (MBBS)",
    category: "Healthcare",
    industry: "Healthcare",
    icon: "🩺",
    tagline: "Diagnose, treat, and improve the health of patients",
    overview:
      "Medical Doctors diagnose and treat illnesses, prescribe medications, and advise patients on health and wellness. Specializations range from General Practice to Surgery, Psychiatry, Cardiology, and more.",
    applicableStages: ["after12th", "afterGraduation"],
    requiredSkills: ["Clinical Diagnosis", "Patient Care", "Medical Knowledge", "Communication", "Decision Making"],
    educationalPath: [
      { level: "10+2 (PCB)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "MBBS", duration: "5.5 years", institutions: ["AIIMS", "JIPMER", "State medical colleges"] },
      { level: "MD/MS (Specialization)", duration: "3 years", institutions: ["PG Medical institutes"] },
    ],
    entranceExams: ["NEET"],
    certifications: ["USMLE (for USA)", "PLAB (for UK)", "DNB", "FMGE (for foreign graduates)"],
    topRecruiters: ["AIIMS", "Apollo", "Fortis", "Max Healthcare", "Government hospitals"],
    futureScope: "India has a massive doctor shortage — 1 doctor per 1,800 patients vs WHO recommended 1:1,000. The demand will only grow with an ageing population.",
    industryDemand: "Very High",
    salaryRange: { min: 6, max: 80 },
    jobRoles: ["General Physician", "Surgeon", "Specialist", "Resident Doctor", "Medical Officer"],
    growthOpportunities: ["Senior Consultant", "Department Head", "Medical Director", "Own Clinic"],
    avgSalary: 15,
    educationYears: 8,
    growthPercent: 18,
  },
  {
    id: "c-nursing",
    title: "Nursing Professional",
    category: "Healthcare",
    industry: "Healthcare",
    icon: "💊",
    tagline: "Provide compassionate care and support to patients",
    overview:
      "Nurses are the backbone of healthcare, providing direct patient care, administering medications, and coordinating with doctors. Opportunities exist in hospitals, schools, NGOs, and abroad.",
    applicableStages: ["after12th", "afterGraduation"],
    requiredSkills: ["Patient Care", "Medical Knowledge", "Communication", "Emergency Response", "Empathy"],
    educationalPath: [
      { level: "10+2 (PCB/any stream)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "B.Sc Nursing / GNM", duration: "3-4 years", institutions: ["Nursing colleges"] },
    ],
    entranceExams: ["NEET (for B.Sc Nursing in some states)"],
    certifications: ["NCLEX-RN (for USA)", "NMC (UK)", "Specialty nursing certifications"],
    topRecruiters: ["AIIMS", "Apollo", "Fortis", "Abroad hospitals (UAE, UK, Canada, Australia)"],
    futureScope: "Global shortage of 6 million nurses by 2030. Indian nurses are in extremely high demand internationally with salaries 10x higher abroad.",
    industryDemand: "Very High",
    salaryRange: { min: 2, max: 20 },
    jobRoles: ["Staff Nurse", "Senior Nurse", "ICU Nurse", "OT Nurse", "Nursing Superintendent"],
    growthOpportunities: ["Chief Nursing Officer", "Nurse Educator", "Nurse Practitioner", "Healthcare Manager"],
    avgSalary: 5,
    educationYears: 4,
    growthPercent: 20,
  },

  // ── Finance ───────────────────────────────────────────────────────────────
  {
    id: "c-chartered-accountant",
    title: "Chartered Accountant (CA)",
    category: "Finance",
    industry: "Finance & Accounting",
    icon: "📊",
    tagline: "Master the language of business — finance, audit, and taxation",
    overview:
      "Chartered Accountants handle financial accounts, taxation, auditing, and financial planning for businesses and individuals. The CA designation is one of the most respected and well-compensated professional qualifications in India.",
    applicableStages: ["after12th", "afterGraduation", "workingProfessional"],
    requiredSkills: ["Accounting", "Taxation", "Auditing", "Financial Analysis", "Corporate Law", "MS Excel"],
    educationalPath: [
      { level: "10+2 (any stream, preferably Commerce)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "CA Foundation → Intermediate → Final", duration: "4-5 years", institutions: ["ICAI"] },
    ],
    entranceExams: ["CA Foundation (ICAI)"],
    certifications: ["CPA (USA)", "ACCA (UK)", "CFA", "CFP"],
    topRecruiters: ["Big 4 (Deloitte, EY, KPMG, PwC)", "RBI", "SEBI", "Major corporates", "Own practice"],
    futureScope: "India adds 50,000 new CAs annually but the demand far exceeds supply. CAs are indispensable for every business.",
    industryDemand: "High",
    salaryRange: { min: 7, max: 50 },
    jobRoles: ["Auditor", "Tax Consultant", "Financial Controller", "CFO", "Independent Practitioner"],
    growthOpportunities: ["Senior Partner", "CFO", "Finance Director", "Own CA Firm"],
    avgSalary: 14,
    educationYears: 5,
    growthPercent: 15,
  },
  {
    id: "c-investment-banker",
    title: "Investment Banker",
    category: "Finance",
    industry: "Finance & Banking",
    icon: "🏦",
    tagline: "Drive mergers, acquisitions, and capital markets at the highest level",
    overview:
      "Investment Bankers help corporations and governments raise capital through equity/debt markets, mergers, acquisitions, and IPOs. It is one of the highest-paying careers in finance.",
    applicableStages: ["afterGraduation", "workingProfessional"],
    requiredSkills: ["Financial Modeling", "Valuation", "Excel", "PowerPoint", "Corporate Finance", "Deal Structuring"],
    educationalPath: [
      { level: "10+2 (any stream)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "B.Com / B.Tech / BA Economics", duration: "3-4 years", institutions: ["IITs", "IIMs (via MBA)", "Top commerce colleges"] },
      { level: "MBA (Finance)", duration: "2 years", institutions: ["IIM A/B/C", "ISB", "IIMs", "Top B-schools"] },
    ],
    entranceExams: ["CAT", "GMAT", "XAT"],
    certifications: ["CFA Level 1/2/3", "FRM", "CAIA"],
    topRecruiters: ["Goldman Sachs", "Morgan Stanley", "JPMorgan", "HSBC", "Kotak", "Axis Capital"],
    futureScope: "As Indian capital markets grow and more startups achieve unicorn status, investment banking demand in India is surging.",
    industryDemand: "High",
    salaryRange: { min: 15, max: 100 },
    jobRoles: ["Analyst", "Associate", "VP", "Director", "Managing Director"],
    growthOpportunities: ["Partner", "Managing Director", "Hedge Fund Manager", "Startup CFO"],
    avgSalary: 30,
    educationYears: 6,
    growthPercent: 20,
  },

  // ── Design ────────────────────────────────────────────────────────────────
  {
    id: "c-ux-designer",
    title: "UX/UI Designer",
    category: "Design",
    industry: "Design / Technology",
    icon: "🎨",
    tagline: "Create digital experiences that delight and empower users",
    overview:
      "UX/UI Designers research user needs, design wireframes, and create beautiful, functional interfaces for apps, websites, and digital products. As every business goes digital, design has become critical.",
    applicableStages: ["after12th", "afterGraduation", "workingProfessional"],
    requiredSkills: ["Figma", "User Research", "Wireframing", "Prototyping", "Design Systems", "Usability Testing"],
    educationalPath: [
      { level: "10+2 (any stream)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "B.Des / BA Design / B.Tech + Design Bootcamp", duration: "3-4 years", institutions: ["NID", "IDC IIT Bombay", "Srishti", "MIT Institute of Design"] },
    ],
    entranceExams: ["UCEED", "NID Entrance", "NIFT"],
    certifications: ["Google UX Design Certificate", "Interaction Design Foundation", "Nielsen Norman UX"],
    topRecruiters: ["Google", "Microsoft", "Swiggy", "Zomato", "Razorpay", "Figma", "Design agencies"],
    futureScope: "With every product needing a digital face, UX design is one of the fastest-growing careers. Senior designers and design leads earn tech-equivalent salaries.",
    industryDemand: "High",
    salaryRange: { min: 5, max: 35 },
    jobRoles: ["UI Designer", "UX Researcher", "Product Designer", "Design Lead", "Head of Design"],
    growthOpportunities: ["Principal Designer", "VP of Design", "Chief Design Officer", "Freelance Consultant"],
    avgSalary: 12,
    educationYears: 4,
    growthPercent: 25,
  },

  // ── Law ───────────────────────────────────────────────────────────────────
  {
    id: "c-lawyer",
    title: "Corporate Lawyer",
    category: "Law",
    industry: "Legal Services",
    icon: "⚖️",
    tagline: "Navigate complex legal landscapes and protect business interests",
    overview:
      "Corporate Lawyers advise businesses on legal matters including contracts, mergers, compliance, intellectual property, and dispute resolution. With India's booming economy, legal expertise is indispensable.",
    applicableStages: ["after12th", "afterGraduation"],
    requiredSkills: ["Legal Research", "Contract Drafting", "Negotiation", "Corporate Law", "Litigation", "Communication"],
    educationalPath: [
      { level: "10+2 (any stream)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "LLB (3-year after graduation) OR BA LLB (5-year integrated)", duration: "3-5 years", institutions: ["NLUs", "Delhi University", "Symbiosis Law School"] },
    ],
    entranceExams: ["CLAT", "AILET", "LSAT"],
    certifications: ["Bar Council Enrollment", "LLM specializations"],
    topRecruiters: ["AZB & Partners", "Cyril Amarchand Mangaldas", "Khaitan & Co", "In-house legal at corporates"],
    futureScope: "India's legal market is growing at 9% annually. Corporate law, M&A, and fintech regulation are the fastest-growing practice areas.",
    industryDemand: "High",
    salaryRange: { min: 5, max: 80 },
    jobRoles: ["Associate", "Senior Associate", "Partner", "In-house Counsel", "Compliance Officer"],
    growthOpportunities: ["Partner at law firm", "General Counsel", "Judge (via judicial services)", "Legal Tech Founder"],
    avgSalary: 15,
    educationYears: 5,
    growthPercent: 12,
  },

  // ── Engineering ───────────────────────────────────────────────────────────
  {
    id: "c-civil-engineer",
    title: "Civil Engineer",
    category: "Engineering",
    industry: "Infrastructure / Construction",
    icon: "🏗️",
    tagline: "Design and build the infrastructure that shapes our world",
    overview:
      "Civil Engineers plan, design, and oversee construction of infrastructure — from roads and bridges to water systems and smart cities. India's massive infrastructure push is creating enormous opportunities.",
    applicableStages: ["after12th", "afterGraduation"],
    requiredSkills: ["AutoCAD", "Structural Analysis", "Project Management", "STAAD Pro", "Surveying", "Material Science"],
    educationalPath: [
      { level: "10+2 (PCM)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "B.Tech Civil Engineering", duration: "4 years", institutions: ["IITs", "NITs", "State engineering colleges"] },
    ],
    entranceExams: ["JEE", "GATE"],
    certifications: ["PMP (Project Management)", "LEED (Green Buildings)", "AutoCAD Certification"],
    topRecruiters: ["L&T", "DLF", "Tata Projects", "NHAI", "PWD", "AECOM", "Shapoorji Pallonji"],
    futureScope: "India's National Infrastructure Pipeline worth ₹111 lakh crore is creating massive demand for civil engineers through 2030.",
    industryDemand: "High",
    salaryRange: { min: 4, max: 25 },
    jobRoles: ["Site Engineer", "Structural Designer", "Project Manager", "Urban Planner", "Consultant"],
    growthOpportunities: ["Project Director", "Chief Engineer", "Own Consultancy", "Government IAS/IES"],
    avgSalary: 8,
    educationYears: 4,
    growthPercent: 14,
  },
  {
    id: "c-mechanical-engineer",
    title: "Mechanical Engineer",
    category: "Engineering",
    industry: "Manufacturing / Automotive",
    icon: "⚙️",
    tagline: "Design and innovate the machines that power our world",
    overview:
      "Mechanical Engineers design, analyze, and manufacture mechanical systems — from automobiles to industrial machinery. With EV and aerospace sectors booming, opportunities are expanding rapidly.",
    applicableStages: ["after12th", "afterGraduation"],
    requiredSkills: ["CAD/CAM", "Thermodynamics", "Manufacturing Processes", "SolidWorks", "FEA", "Robotics"],
    educationalPath: [
      { level: "10+2 (PCM)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "B.Tech Mechanical Engineering", duration: "4 years", institutions: ["IITs", "NITs", "State engineering colleges"] },
    ],
    entranceExams: ["JEE", "GATE"],
    certifications: ["SolidWorks Certification", "PMP", "Six Sigma"],
    topRecruiters: ["TATA Motors", "Mahindra", "Maruti Suzuki", "ISRO", "DRDO", "Bosch", "Siemens"],
    futureScope: "India's EV revolution, defense modernization, and aerospace growth are creating exciting new roles for mechanical engineers.",
    industryDemand: "High",
    salaryRange: { min: 4, max: 30 },
    jobRoles: ["Design Engineer", "Production Engineer", "R&D Engineer", "Quality Engineer", "Consultant"],
    growthOpportunities: ["Senior Manager", "Plant Head", "Technical Director", "Startup Founder"],
    avgSalary: 9,
    educationYears: 4,
    growthPercent: 12,
  },

  // ── Business ──────────────────────────────────────────────────────────────
  {
    id: "c-product-manager",
    title: "Product Manager",
    category: "Business",
    industry: "Technology / Business",
    icon: "📱",
    tagline: "Lead products from idea to impact at scale",
    overview:
      "Product Managers own the strategy, roadmap, and execution of digital products. They work at the intersection of business, technology, and user experience — making them the 'CEO of the product'.",
    applicableStages: ["afterGraduation", "workingProfessional"],
    requiredSkills: ["Product Strategy", "User Research", "Data Analysis", "Agile", "Communication", "Roadmapping"],
    educationalPath: [
      { level: "10+2 (any stream)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "B.Tech or B.Com or BA + relevant experience", duration: "3-4 years", institutions: ["IITs", "Top colleges"] },
      { level: "MBA (optional but accelerates)", duration: "2 years", institutions: ["IIMs", "ISB", "Top B-schools"] },
    ],
    entranceExams: ["CAT", "GMAT"],
    certifications: ["Google PM Certificate", "PMI-ACP", "Product School PM Certificate"],
    topRecruiters: ["Google", "Amazon", "Flipkart", "Swiggy", "Razorpay", "Startups"],
    futureScope: "Every tech product needs a PM. With India's startup ecosystem booming, PM roles are among the most sought-after and well-paid non-engineering roles in tech.",
    industryDemand: "High",
    salaryRange: { min: 10, max: 60 },
    jobRoles: ["Associate PM", "Product Manager", "Senior PM", "Group PM", "VP Product"],
    growthOpportunities: ["Chief Product Officer", "Co-founder", "VC Partner", "Head of Business"],
    avgSalary: 20,
    educationYears: 4,
    growthPercent: 28,
  },
  {
    id: "c-marketing-manager",
    title: "Digital Marketing Manager",
    category: "Business",
    industry: "Marketing / Business",
    icon: "📣",
    tagline: "Build brands and acquire customers in the digital world",
    overview:
      "Digital Marketing Managers develop and execute online marketing strategies across SEO, social media, paid ads, email, and content — driving brand growth and customer acquisition.",
    applicableStages: ["after12th", "afterGraduation", "workingProfessional"],
    requiredSkills: ["SEO/SEM", "Social Media Marketing", "Google Ads", "Content Strategy", "Analytics", "Email Marketing"],
    educationalPath: [
      { level: "10+2 (any stream)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "BBA / B.Com / BA / Any degree", duration: "3 years", institutions: ["Any university"] },
    ],
    entranceExams: ["CUET", "University-specific exams"],
    certifications: ["Google Digital Marketing", "HubSpot Marketing", "Meta Blueprint", "SEMrush Academy"],
    topRecruiters: ["Google", "Meta", "Amazon", "Myntra", "Nykaa", "Digital agencies", "Startups"],
    futureScope: "India's digital ad market is growing at 25% annually. Every brand needs digital marketers, making this one of the most accessible high-growth careers.",
    industryDemand: "High",
    salaryRange: { min: 4, max: 25 },
    jobRoles: ["SEO Specialist", "Social Media Manager", "Content Marketer", "Performance Marketer", "CMO"],
    growthOpportunities: ["Head of Marketing", "CMO", "Marketing Consultant", "Agency Founder"],
    avgSalary: 9,
    educationYears: 3,
    growthPercent: 25,
  },

  // ── Education ─────────────────────────────────────────────────────────────
  {
    id: "c-teacher",
    title: "School Teacher / Educator",
    category: "Education",
    industry: "Education",
    icon: "🎓",
    tagline: "Shape the minds and futures of the next generation",
    overview:
      "Teachers inspire, educate, and guide students through critical formative years. With EdTech booming, opportunities for educators have expanded beyond classrooms to online platforms reaching millions.",
    applicableStages: ["after12th", "afterGraduation"],
    requiredSkills: ["Subject Expertise", "Communication", "Classroom Management", "Patience", "Curriculum Design", "EdTech Tools"],
    educationalPath: [
      { level: "10+2 (any stream)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "BA / B.Sc / B.Com (relevant subject)", duration: "3 years", institutions: ["Any university"] },
      { level: "B.Ed (Bachelor of Education)", duration: "2 years", institutions: ["B.Ed colleges, Universities"] },
    ],
    entranceExams: ["CUET", "CTET", "State TET exams"],
    certifications: ["CTET", "State TET", "Google Educator", "UGC-NET (for college teaching)"],
    topRecruiters: ["Government schools", "CBSE/ICSE private schools", "BYJU'S", "Unacademy", "Vedantu", "International schools"],
    futureScope: "India needs 2 million more teachers by 2030. EdTech platforms have created paths for educators to earn ₹50L+ annually as online instructors.",
    industryDemand: "Very High",
    salaryRange: { min: 3, max: 30 },
    jobRoles: ["Primary Teacher", "Secondary Teacher", "PGT", "Online Educator", "Curriculum Designer"],
    growthOpportunities: ["Principal", "School Director", "EdTech Content Creator", "Academic Administrator"],
    avgSalary: 6,
    educationYears: 5,
    growthPercent: 15,
  },

  // ── Science ───────────────────────────────────────────────────────────────
  {
    id: "c-research-scientist",
    title: "Research Scientist",
    category: "Science",
    industry: "Research & Development",
    icon: "🔬",
    tagline: "Push the boundaries of human knowledge through scientific discovery",
    overview:
      "Research Scientists conduct experiments and studies to advance knowledge in fields like physics, chemistry, biology, or materials science. They work in universities, government labs, and private R&D centres.",
    applicableStages: ["afterGraduation", "workingProfessional"],
    requiredSkills: ["Research Methodology", "Data Analysis", "Scientific Writing", "Lab Skills", "Critical Thinking", "Statistics"],
    educationalPath: [
      { level: "10+2 (PCM/PCB)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "B.Sc (relevant field)", duration: "3 years", institutions: ["IISc", "Central universities", "State universities"] },
      { level: "M.Sc + PhD", duration: "5-6 years", institutions: ["IISc", "IITs", "TIFR", "CSIR labs"] },
    ],
    entranceExams: ["JEE (for IIT B.Sc)","GATE", "JEST", "JAM", "CSIR-UGC NET"],
    certifications: ["Fellowship programs (DST, DBT)", "International research fellowships"],
    topRecruiters: ["CSIR", "ISRO", "DRDO", "BARC", "IITs", "IISc", "Pharma R&D (Sun Pharma, Dr Reddy's)"],
    futureScope: "India's R&D investment is growing, and government initiatives like NRF (National Research Foundation) with ₹50,000 crore funding are creating unprecedented opportunities.",
    industryDemand: "Medium",
    salaryRange: { min: 6, max: 30 },
    jobRoles: ["Research Associate", "Scientist B/C/D", "Principal Scientist", "Fellow", "Professor"],
    growthOpportunities: ["Lab Director", "Professor", "Startup Founder (DeepTech)", "International Research Fellow"],
    avgSalary: 12,
    educationYears: 9,
    growthPercent: 18,
  },

  // ── Government ────────────────────────────────────────────────────────────
  {
    id: "c-ias-officer",
    title: "IAS / Civil Services Officer",
    category: "Government",
    industry: "Government / Public Service",
    icon: "🏛️",
    tagline: "Lead India's administration and shape public policy at the highest level",
    overview:
      "IAS (Indian Administrative Service) officers are the backbone of India's civil administration, implementing government policies, managing districts, and leading departments. It is one of India's most prestigious and impactful careers.",
    applicableStages: ["afterGraduation", "workingProfessional"],
    requiredSkills: ["Leadership", "Policy Analysis", "Administration", "Communication", "Decision Making", "Ethics"],
    educationalPath: [
      { level: "10+2 (any stream)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "Any Graduation (any subject)", duration: "3-4 years", institutions: ["Any recognized university"] },
    ],
    entranceExams: ["UPSC CSE (Prelims + Mains + Interview)"],
    certifications: ["IAS Training (LBSNAA)", "Various government capacity building programs"],
    topRecruiters: ["Government of India (Central Services)", "State Governments"],
    futureScope: "Civil services remain the most prestigious career in India with unmatched job security, perks, and opportunity to create lasting societal impact.",
    industryDemand: "High",
    salaryRange: { min: 8, max: 18 },
    jobRoles: ["SDM", "District Collector", "Joint Secretary", "Secretary", "Cabinet Secretary"],
    growthOpportunities: ["Chief Secretary", "Secretary to Government of India", "Governor", "Ambassador"],
    avgSalary: 12,
    educationYears: 4,
    growthPercent: 5,
  },

  // ── Arts & Media ──────────────────────────────────────────────────────────
  {
    id: "c-journalist",
    title: "Journalist / Media Professional",
    category: "Arts & Media",
    industry: "Media & Journalism",
    icon: "📰",
    tagline: "Inform, investigate, and hold power accountable through storytelling",
    overview:
      "Journalists research, write, and report news across print, digital, and broadcast media. With digital media booming, opportunities range from traditional newsrooms to podcasts, YouTube, and independent journalism.",
    applicableStages: ["after12th", "afterGraduation", "workingProfessional"],
    requiredSkills: ["Writing", "Research", "Interviewing", "Video Production", "Social Media", "Fact-checking"],
    educationalPath: [
      { level: "10+2 (any stream)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "BA Journalism / Mass Communication", duration: "3 years", institutions: ["IIMC", "Jamia Millia", "Symbiosis", "ACJ Chennai"] },
    ],
    entranceExams: ["IIMC Entrance", "Jamia Entrance", "CUET"],
    certifications: ["Digital Journalism (Google)", "Video Production (Adobe)", "Data Journalism"],
    topRecruiters: ["The Hindu", "NDTV", "Times of India", "Mint", "The Wire", "Reuters", "BBC India"],
    futureScope: "Digital media consumption in India is at an all-time high. Independent journalism and content creation offer unprecedented income potential.",
    industryDemand: "Medium",
    salaryRange: { min: 3, max: 25 },
    jobRoles: ["Reporter", "Sub-editor", "Anchor", "Editor", "Content Creator", "Independent Journalist"],
    growthOpportunities: ["Editor-in-Chief", "Media Owner", "Author", "Independent Creator (YouTube/Podcast)"],
    avgSalary: 7,
    educationYears: 3,
    growthPercent: 10,
  },

  // ── Additional ────────────────────────────────────────────────────────────
  {
    id: "c-psychologist",
    title: "Clinical Psychologist",
    category: "Healthcare",
    industry: "Mental Health / Healthcare",
    icon: "🧠",
    tagline: "Help people understand and overcome mental health challenges",
    overview:
      "Clinical Psychologists assess, diagnose, and treat mental health disorders through therapy and counselling. With mental health awareness rising in India, this field is experiencing rapid growth.",
    applicableStages: ["afterGraduation", "workingProfessional"],
    requiredSkills: ["Counselling", "Psychotherapy", "Assessment", "Empathy", "Research", "CBT/DBT"],
    educationalPath: [
      { level: "10+2 (any stream, preferably Science)", duration: "2 years", institutions: ["Any recognized board"] },
      { level: "BA/B.Sc Psychology", duration: "3 years", institutions: ["Universities"] },
      { level: "MA/M.Sc Psychology + M.Phil (Clinical)", duration: "4 years", institutions: ["NIMHANS", "AIIMS", "Universities"] },
    ],
    entranceExams: ["CUET", "RCI (Rehabilitation Council of India) Entrance"],
    certifications: ["RCI License", "CBT Certification", "Mindfulness-Based Therapy"],
    topRecruiters: ["NIMHANS", "AIIMS", "Private hospitals", "NGOs", "Relicus (🎉)", "Corporate EAP"],
    futureScope: "India has only 0.07 psychiatrists per 100,000 people. Mental health awareness is surging — making psychologists among the most needed professionals in India.",
    industryDemand: "Very High",
    salaryRange: { min: 4, max: 25 },
    jobRoles: ["Counselling Psychologist", "School Psychologist", "Corporate Wellness Lead", "Therapist", "Researcher"],
    growthOpportunities: ["Head of Psychology Dept", "Private Practice", "NGO Director", "Academic"],
    avgSalary: 8,
    educationYears: 7,
    growthPercent: 22,
  },
  {
    id: "c-entrepreneur",
    title: "Entrepreneur / Startup Founder",
    category: "Business",
    industry: "Startup / Business",
    icon: "🚀",
    tagline: "Build solutions that create value and employment for others",
    overview:
      "Entrepreneurs identify problems and build businesses to solve them. India's startup ecosystem — the world's 3rd largest — offers unparalleled opportunities for those willing to take the leap.",
    applicableStages: ["after12th", "afterGraduation", "workingProfessional"],
    requiredSkills: ["Problem Solving", "Leadership", "Business Model Design", "Sales", "Resilience", "Team Building"],
    educationalPath: [
      { level: "Any educational background", duration: "varies", institutions: ["No fixed path — learn by doing"] },
      { level: "MBA or Accelerator Programs (optional)", duration: "1-2 years", institutions: ["IIMs", "Y Combinator", "Techstars"] },
    ],
    entranceExams: [],
    certifications: ["Startup India Recognition", "GST Registration", "Any domain certification"],
    topRecruiters: ["Self-employed — you build the company!"],
    futureScope: "India has 100+ unicorns and the government's Startup India program supports new ventures. The next decade will see India create 10,000+ new startups annually.",
    industryDemand: "High",
    salaryRange: { min: 0, max: 1000 },
    jobRoles: ["Founder", "Co-founder", "CEO", "Managing Director", "Partner"],
    growthOpportunities: ["Unicorn Founder", "Serial Entrepreneur", "Angel Investor", "VC Partner"],
    avgSalary: 0,
    educationYears: 0,
    growthPercent: 35,
  },
];

export const CAREER_CATEGORIES = [
  "All", "Technology", "Healthcare", "Finance", "Engineering",
  "Design", "Law", "Business", "Education", "Science", "Government", "Arts & Media"
] as const;
