import { Industry } from "../../app/knowNext/types";

export const INDUSTRIES: Industry[] = [
  {
    id: "ind-technology",
    name: "Technology & IT",
    icon: "💻",
    description: "India's largest and fastest-growing sector, spanning software, AI, cloud, cybersecurity, and digital products. Home to 5 million+ IT professionals and a booming startup ecosystem.",
    growthPercent: 28,
    avgSalaryLPA: 14,
    trendingCareers: ["AI/ML Engineer", "Data Scientist", "Cloud Architect", "Cybersecurity Analyst", "Product Manager"],
    topRecruiters: ["TCS", "Infosys", "Wipro", "Accenture", "Google", "Microsoft", "Amazon", "Flipkart", "Razorpay", "Zepto"],
    futureOpportunities: ["Generative AI products", "Quantum computing", "Edge computing", "Web3 / Blockchain", "AR/VR development"],
    marketTrends: {
      salaryTrend: [
        { year: "2020", value: 9 },
        { year: "2021", value: 10 },
        { year: "2022", value: 12 },
        { year: "2023", value: 14 },
        { year: "2024", value: 16 },
        { year: "2025", value: 19 },
      ],
      demandTrend: [
        { year: "2020", value: 65 },
        { year: "2021", value: 72 },
        { year: "2022", value: 80 },
        { year: "2023", value: 88 },
        { year: "2024", value: 93 },
        { year: "2025", value: 98 },
      ],
      hiringTrend: [
        { year: "2020", value: 220000 },
        { year: "2021", value: 290000 },
        { year: "2022", value: 400000 },
        { year: "2023", value: 340000 },
        { year: "2024", value: 380000 },
        { year: "2025", value: 430000 },
      ],
      emergingTechnologies: ["Generative AI (LLMs)", "Quantum Computing", "Edge AI", "Web3", "AR/VR/Metaverse", "Autonomous Systems"],
      futureSkills: ["Prompt Engineering", "LLM Fine-tuning", "MLOps", "Cloud-Native Dev", "Cybersecurity", "System Design"],
    },
  },
  {
    id: "ind-healthcare",
    name: "Healthcare & Life Sciences",
    icon: "🏥",
    description: "India's healthcare sector is undergoing a massive transformation — from telemedicine to hospital chains to pharma R&D. Expected to reach $372 billion by 2022 and grow rapidly post-COVID.",
    growthPercent: 22,
    avgSalaryLPA: 10,
    trendingCareers: ["Doctor (MBBS/MD)", "Clinical Psychologist", "Healthcare Data Analyst", "Medical Device Engineer", "Pharmacist"],
    topRecruiters: ["AIIMS", "Apollo Hospitals", "Fortis Healthcare", "Manipal Health", "Sun Pharma", "Dr. Reddy's", "Cipla", "Practo", "1mg"],
    futureOpportunities: ["Digital health platforms", "AI diagnostics", "Genomics", "Medical tourism", "Mental health tech"],
    marketTrends: {
      salaryTrend: [
        { year: "2020", value: 7 },
        { year: "2021", value: 7.5 },
        { year: "2022", value: 8.5 },
        { year: "2023", value: 10 },
        { year: "2024", value: 11 },
        { year: "2025", value: 13 },
      ],
      demandTrend: [
        { year: "2020", value: 70 },
        { year: "2021", value: 78 },
        { year: "2022", value: 82 },
        { year: "2023", value: 86 },
        { year: "2024", value: 91 },
        { year: "2025", value: 95 },
      ],
      hiringTrend: [
        { year: "2020", value: 120000 },
        { year: "2021", value: 160000 },
        { year: "2022", value: 200000 },
        { year: "2023", value: 220000 },
        { year: "2024", value: 260000 },
        { year: "2025", value: 310000 },
      ],
      emergingTechnologies: ["AI-powered Diagnostics", "Telemedicine Platforms", "Genomic Sequencing", "Wearable Health Devices", "Robot-assisted Surgery"],
      futureSkills: ["Healthcare Data Analytics", "Digital Health Product Design", "Bioinformatics", "Clinical Research", "Mental Health Counselling"],
    },
  },
  {
    id: "ind-finance",
    name: "Finance & Banking",
    icon: "🏦",
    description: "India's financial sector is booming — from fintech unicorns to traditional banking reforms. The UPI revolution has made India a global fintech leader.",
    growthPercent: 18,
    avgSalaryLPA: 15,
    trendingCareers: ["Investment Banker", "Chartered Accountant", "Financial Analyst", "Fintech Product Manager", "Wealth Manager"],
    topRecruiters: ["SBI", "HDFC Bank", "ICICI Bank", "Axis Bank", "Goldman Sachs", "Morgan Stanley", "Deloitte", "EY", "Razorpay", "Zerodha"],
    futureOpportunities: ["Digital banking products", "Crypto regulation", "Embedded finance", "Insurance tech", "MSME lending"],
    marketTrends: {
      salaryTrend: [
        { year: "2020", value: 10 },
        { year: "2021", value: 11 },
        { year: "2022", value: 13 },
        { year: "2023", value: 15 },
        { year: "2024", value: 17 },
        { year: "2025", value: 20 },
      ],
      demandTrend: [
        { year: "2020", value: 60 },
        { year: "2021", value: 65 },
        { year: "2022", value: 72 },
        { year: "2023", value: 78 },
        { year: "2024", value: 84 },
        { year: "2025", value: 90 },
      ],
      hiringTrend: [
        { year: "2020", value: 90000 },
        { year: "2021", value: 110000 },
        { year: "2022", value: 140000 },
        { year: "2023", value: 160000 },
        { year: "2024", value: 180000 },
        { year: "2025", value: 210000 },
      ],
      emergingTechnologies: ["RegTech (Regulatory Technology)", "Blockchain & DeFi", "AI-powered Credit Scoring", "Open Banking APIs", "CBDC (Digital Rupee)"],
      futureSkills: ["Financial Modelling", "CFA / FRM", "Fintech Product Management", "Risk Analytics", "Compliance & RegTech"],
    },
  },
  {
    id: "ind-education",
    name: "Education & EdTech",
    icon: "📚",
    description: "India's education sector is being transformed by EdTech giants and government reforms. With NEP 2020, there's unprecedented demand for innovative educators and ed-tech professionals.",
    growthPercent: 20,
    avgSalaryLPA: 7,
    trendingCareers: ["School Teacher", "EdTech Content Creator", "Instructional Designer", "Online Tutor", "Education Consultant"],
    topRecruiters: ["BYJU'S", "Unacademy", "Vedantu", "PhysicsWallah", "Eruditus", "upGrad", "Government schools", "CBSE private schools"],
    futureOpportunities: ["AI-personalized learning", "VR classrooms", "Micro-credentialing", "Adult reskilling", "Vernacular EdTech"],
    marketTrends: {
      salaryTrend: [
        { year: "2020", value: 5 },
        { year: "2021", value: 5.5 },
        { year: "2022", value: 6 },
        { year: "2023", value: 7 },
        { year: "2024", value: 8 },
        { year: "2025", value: 9 },
      ],
      demandTrend: [
        { year: "2020", value: 72 },
        { year: "2021", value: 80 },
        { year: "2022", value: 85 },
        { year: "2023", value: 88 },
        { year: "2024", value: 91 },
        { year: "2025", value: 95 },
      ],
      hiringTrend: [
        { year: "2020", value: 150000 },
        { year: "2021", value: 200000 },
        { year: "2022", value: 220000 },
        { year: "2023", value: 240000 },
        { year: "2024", value: 260000 },
        { year: "2025", value: 290000 },
      ],
      emergingTechnologies: ["AI Tutors (LLM-based)", "VR Classrooms", "Adaptive Learning Platforms", "Game-based Learning", "Learning Management Systems"],
      futureSkills: ["Instructional Design", "EdTech Product Management", "Online Course Creation", "Learning Analytics", "AI in Education"],
    },
  },
  {
    id: "ind-manufacturing",
    name: "Manufacturing & Engineering",
    icon: "⚙️",
    description: "Make in India and PLI (Production Linked Incentive) schemes are transforming manufacturing. Defense, EV, aerospace, and semiconductor sectors are creating new engineering opportunities.",
    growthPercent: 14,
    avgSalaryLPA: 8,
    trendingCareers: ["Mechanical Engineer", "Civil Engineer", "EV Engineer", "Aerospace Engineer", "Industrial Designer"],
    topRecruiters: ["TATA Motors", "Mahindra", "Maruti Suzuki", "L&T", "ISRO", "DRDO", "Bosch", "Siemens", "Samsung", "Apple (India manufacturing)"],
    futureOpportunities: ["EV supply chain", "Semiconductor manufacturing", "Defense & aerospace", "Smart factories (Industry 4.0)", "Green energy infrastructure"],
    marketTrends: {
      salaryTrend: [
        { year: "2020", value: 6 },
        { year: "2021", value: 6.5 },
        { year: "2022", value: 7 },
        { year: "2023", value: 8 },
        { year: "2024", value: 9 },
        { year: "2025", value: 10 },
      ],
      demandTrend: [
        { year: "2020", value: 55 },
        { year: "2021", value: 58 },
        { year: "2022", value: 62 },
        { year: "2023", value: 68 },
        { year: "2024", value: 74 },
        { year: "2025", value: 80 },
      ],
      hiringTrend: [
        { year: "2020", value: 80000 },
        { year: "2021", value: 90000 },
        { year: "2022", value: 110000 },
        { year: "2023", value: 130000 },
        { year: "2024", value: 150000 },
        { year: "2025", value: 175000 },
      ],
      emergingTechnologies: ["Industry 4.0 / Smart Factories", "Electric Vehicle Tech", "Semiconductor Fabrication", "3D Printing / Additive Manufacturing", "Robotic Process Automation"],
      futureSkills: ["EV Engineering", "Robotics & Automation", "CAD/CAM", "Supply Chain Management", "Quality 4.0"],
    },
  },
  {
    id: "ind-media",
    name: "Media & Creative Industries",
    icon: "🎬",
    description: "India's media industry is seeing a digital revolution — from OTT platforms to creator economy to gaming. The creator economy alone has 100 million+ creators in India.",
    growthPercent: 16,
    avgSalaryLPA: 7,
    trendingCareers: ["Content Creator / YouTuber", "UX/UI Designer", "Journalist", "Digital Marketer", "Game Developer"],
    topRecruiters: ["Netflix India", "Amazon Prime", "Hotstar", "ZEE5", "Sony LIV", "Spotify", "Times of India", "NDTV", "WPP", "Dentsu"],
    futureOpportunities: ["OTT content creation", "Gaming & esports", "NFT and digital art", "Podcast production", "AI-generated media"],
    marketTrends: {
      salaryTrend: [
        { year: "2020", value: 5 },
        { year: "2021", value: 5.5 },
        { year: "2022", value: 6.5 },
        { year: "2023", value: 7.5 },
        { year: "2024", value: 8.5 },
        { year: "2025", value: 10 },
      ],
      demandTrend: [
        { year: "2020", value: 55 },
        { year: "2021", value: 62 },
        { year: "2022", value: 70 },
        { year: "2023", value: 76 },
        { year: "2024", value: 82 },
        { year: "2025", value: 88 },
      ],
      hiringTrend: [
        { year: "2020", value: 50000 },
        { year: "2021", value: 65000 },
        { year: "2022", value: 80000 },
        { year: "2023", value: 90000 },
        { year: "2024", value: 105000 },
        { year: "2025", value: 125000 },
      ],
      emergingTechnologies: ["AI Video Generation", "Generative Art & Music", "AR/VR Storytelling", "Interactive Media", "Gaming Engines (Unity/Unreal)"],
      futureSkills: ["Video Production", "Graphic Design", "SEO/SEM", "Social Media Management", "Brand Strategy", "Copywriting"],
    },
  },
  {
    id: "ind-legal",
    name: "Legal & Compliance",
    icon: "⚖️",
    description: "India's legal market is growing at 9% annually. Corporate law, M&A, fintech regulation, and data privacy are the fastest-growing practice areas as India becomes a global business hub.",
    growthPercent: 12,
    avgSalaryLPA: 12,
    trendingCareers: ["Corporate Lawyer", "Compliance Officer", "Legal Tech Specialist", "IP Lawyer", "Arbitration Specialist"],
    topRecruiters: ["AZB & Partners", "Cyril Amarchand Mangaldas", "Khaitan & Co", "J Sagar Associates", "In-house legal at corporates", "SEBI", "RBI"],
    futureOpportunities: ["Data privacy law (DPDP Act)", "Fintech regulation", "AI ethics & law", "International arbitration", "Legal tech platforms"],
    marketTrends: {
      salaryTrend: [
        { year: "2020", value: 8 },
        { year: "2021", value: 9 },
        { year: "2022", value: 11 },
        { year: "2023", value: 13 },
        { year: "2024", value: 15 },
        { year: "2025", value: 18 },
      ],
      demandTrend: [
        { year: "2020", value: 50 },
        { year: "2021", value: 55 },
        { year: "2022", value: 60 },
        { year: "2023", value: 66 },
        { year: "2024", value: 72 },
        { year: "2025", value: 80 },
      ],
      hiringTrend: [
        { year: "2020", value: 20000 },
        { year: "2021", value: 24000 },
        { year: "2022", value: 28000 },
        { year: "2023", value: 33000 },
        { year: "2024", value: 38000 },
        { year: "2025", value: 44000 },
      ],
      emergingTechnologies: ["Legal Research AI (Harvey)", "Contract Review Automation", "E-discovery Tools", "Blockchain for Legal Contracts", "RegTech"],
      futureSkills: ["Data Privacy Law (DPDP)", "M&A Due Diligence", "Legal Research (AI-assisted)", "International Arbitration", "IP & Patent Law"],
    },
  },
  {
    id: "ind-government",
    name: "Government & Public Sector",
    icon: "🏛️",
    description: "India's public sector offers unmatched job security, prestige, and social impact. From IAS to defence to PSUs — government careers are highly competitive and rewarding.",
    growthPercent: 6,
    avgSalaryLPA: 9,
    trendingCareers: ["IAS Officer", "IPS Officer", "PSU Engineer", "Bank PO", "Defence Officer"],
    topRecruiters: ["UPSC (IAS/IPS/IFS)", "SSC", "IBPS", "State PSCs", "DRDO", "ISRO", "NTPC", "ONGC", "HAL", "Indian Army/Navy/Air Force"],
    futureOpportunities: ["Digital governance", "Smart city administration", "Defence modernization", "Green energy PSUs", "AI in government"],
    marketTrends: {
      salaryTrend: [
        { year: "2020", value: 7 },
        { year: "2021", value: 7.5 },
        { year: "2022", value: 8 },
        { year: "2023", value: 8.5 },
        { year: "2024", value: 9 },
        { year: "2025", value: 9.5 },
      ],
      demandTrend: [
        { year: "2020", value: 80 },
        { year: "2021", value: 82 },
        { year: "2022", value: 84 },
        { year: "2023", value: 86 },
        { year: "2024", value: 88 },
        { year: "2025", value: 90 },
      ],
      hiringTrend: [
        { year: "2020", value: 200000 },
        { year: "2021", value: 180000 },
        { year: "2022", value: 210000 },
        { year: "2023", value: 190000 },
        { year: "2024", value: 220000 },
        { year: "2025", value: 230000 },
      ],
      emergingTechnologies: ["e-Governance platforms", "Digital India Stack", "GovTech AI", "Satellite-based services", "Digital forensics"],
      futureSkills: ["Public Policy Analysis", "Digital Governance", "Project Management (PMGSY)", "Data Science for Policy", "GIS & Remote Sensing"],
    },
  },
];
